FROM node:20-alpine AS builder
WORKDIR /app
# vite build üçün lazım ola bilər
RUN apk add --no-cache python3 make g++
# yalnız frontend paketləri
COPY package.frontend.json ./package.json
COPY vite.config.ts tsconfig*.json ./
COPY src/ ./src/
RUN npm install --legacy-peer-deps
RUN npm run build

FROM nginx:alpine
RUN mkdir -p /app/nginx-logs
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80