import { SiteContent } from './types';

// Compile-time fallback. Canonical live content is written to data/site-content.json via the admin UI.
export const DEFAULT_SITE_CONTENT: SiteContent = {
  about: {
    hero: {
      badge: { az: 'Bizim Hekayəmiz', en: 'Our Story', ru: 'Наша история', tr: 'Hikayemiz' },
      titleLine1: { az: 'Keyfiyyət.', en: 'Quality.', ru: 'Качество.', tr: 'Kalite.' },
      titleLine2: { az: 'Təcrübə.', en: 'Experience.', ru: 'Опыт.', tr: 'Deneyim.' },
      subtitle: { az: 'Tədbiriniz üçün hər şey — Operativlik və Bol çeşidin vəhdəti.', en: 'Everything for your event — the unity of efficiency and vast variety.', ru: 'Всё для вашего мероприятия — единство оперативности и богатого ассортимента.', tr: 'Etkinliğiniz için her şey — verimlilik ve geniş çeşitlilik.' },
    },
    partnerIntro: {
      badge: { az: 'Tərəfdaşınız', en: 'Your Partner', ru: 'Ваш партнёр', tr: 'Ortağınız' },
      titleLine1: { az: 'Biz', en: 'Who', ru: 'Кто', tr: 'Biz' },
      titleLine2: { az: 'Kimik.', en: 'We Are.', ru: 'Мы есть.', tr: 'Kimiz.' },
      quote: { az: '"Event Rent" olaraq biz, tədbirlərin təşkili və texniki təchizatı sahəsində uzun illərdir ki, peşəkar xidmət göstəririk. Missiyamız müştərilərimizə ən müasir texnologiyaları və yaradıcı həlləri təqdim edərək, onların tədbirlərini unudulmaz etməyimizdir.', en: 'As "Event Rent", we have been providing professional services in event organization and technical equipment for many years. Our mission is to deliver the latest technologies and creative solutions to our clients, making their events unforgettable.', ru: 'Как «Event Rent» мы уже много лет профессионально оказываем услуги в сфере организации мероприятий и технического оснащения. Наша миссия — предоставлять клиентам передовые технологии и творческие решения, делая их события незабываемыми.', tr: '"Event Rent" olarak yıllardır etkinlik organizasyonu ve teknik teçhizat alanında profesyonel hizmet sunuyoruz. Misyonumuz, müşterilerimize en modern teknolojileri ve yaratıcı çözümleri sunarak etkinliklerini unutulmaz kılmaktır.' },
      stats: [
        { value: '500+', label: { az: 'Uğurlu Tədbir', en: 'Successful Events', ru: 'Успешных мероприятий', tr: 'Başarılı Etkinlik' } },
        { value: '1000+', label: { az: 'Avadanlıq Çeşidi', en: 'Equipment Varieties', ru: 'Видов оборудования', tr: 'Ekipman Çeşidi' } },
      ],
    },
    approach: {
      badge: { az: 'Haqqımızda', en: 'About Us', ru: 'О нас', tr: 'Hakkımızda' },
      titleLine1: { az: 'Yanaşma', en: 'Our', ru: 'Наш', tr: 'Yaklaşım' },
      titleLine2: { az: 'Fəlsəfəmiz.', en: 'Philosophy.', ru: 'Подход.', tr: 'Felsefemiz.' },
      steps: [
        { n: '01', title: { az: 'Fərqli Baxış', en: 'Different Perspective', ru: 'Другой взгляд', tr: 'Farklı Bakış' }, text: { az: 'Biz tədbirlərə sadəcə təşkil olunacaq bir iş kimi baxmırıq.', en: 'We do not view events simply as tasks to be organized.', ru: 'Мы не рассматриваем мероприятия просто как работу.', tr: 'Etkinliklere sadece organize edilecek bir iş olarak bakmıyoruz.' } },
        { n: '02', title: { az: 'Atmosfer Yaradan', en: 'Atmosphere Creator', ru: 'Создатель атмосферы', tr: 'Atmosfer Yaratıcısı' }, text: { az: 'İnsanlar bir tədbirin tərtibatını yox, atmosferini xatırlayırlar.', en: 'People remember the atmosphere of an event, not just its arrangement.', ru: 'Люди запоминают атмосферу мероприятия, а не просто его организацию.', tr: 'İnsanlar etkinliğin düzenini değil, atmosferini hatırlar.' } },
        { n: '03', title: { az: 'Şablon Yoxdur', en: 'No Templates', ru: 'Без шаблонов', tr: 'Şablon Yok' }, text: { az: 'Hər müştərinin ehtiyacı, hər tədbirin ritmi və hər brendin öz xarakteri var.', en: 'Every client has unique needs, every event its rhythm, every brand its character.', ru: 'У каждого клиента свои потребности, у каждого мероприятия — свой ритм, у каждого бренда — свой характер.', tr: 'Her müşterinin ihtiyacı, her etkinliğin ritmi ve her markanın kendine özgü karakteri vardır.' } },
        { n: '04', title: { az: 'Dərin Anlama', en: 'Deep Understanding', ru: 'Глубокое понимание', tr: 'Derin Anlayış' }, text: { az: 'Müştərinin məqsədini, auditoriyasını və yaratmaq istədiyi hissi anlayırıq.', en: 'We understand the client\'s goals, audience, and the feeling they want to create.', ru: 'Мы понимаем цели клиента, его аудиторию и ощущение, которое он хочет создать.', tr: 'Müşterinin hedeflerini, kitlesini ve yaratmak istediği hissi anlıyoruz.' } },
        { n: '05', title: { az: 'Dinamik Fərq', en: 'Dynamic Difference', ru: 'Динамичное отличие', tr: 'Dinamik Fark' }, text: { az: 'Bəzən protokol və dəqiqlik, bəzən emosional enerji tələb olunur.', en: 'Sometimes precision and protocol are needed, sometimes emotional energy.', ru: 'Иногда нужны точность и протокол, иногда — эмоциональная энергия.', tr: 'Bazen hassasiyet ve protokol, bazen duygusal enerji gereklidir.' } },
        { n: '06', title: { az: 'Vahid Sistem', en: 'Unified System', ru: 'Единая система', tr: 'Birleşik Sistem' }, text: { az: 'İlk ideyadan son saniyəyə kreativlik, texnologiya və operativ təminatı birləşdiririk.', en: 'From first idea to last second, we unite creativity, technology and operational support.', ru: 'От первой идеи до последней секунды мы объединяем творчество, технологии и оперативное обеспечение.', tr: 'İlk fikirden son saniyeye yaratıcılık, teknoloji ve operasyonel desteği birleştiriyoruz.' } },
      ],
    },
    visionMission: {
      badge: { az: 'Kimik', en: 'Who We Are', ru: 'Кто мы', tr: 'Kimiz' },
      visionLabel: { az: '01 — Vizyon', en: '01 — Vision', ru: '01 — Видение', tr: '01 — Vizyon' },
      visionTitle: { az: 'VİZYONUMUZ', en: 'OUR VISION', ru: 'НАШ ВЗГЛЯД', tr: 'VİZYONUMUZ' },
      visionBody: { az: 'Tədbir üçün bütün infrastruktur, avadanlıq və həlləri bir mərkəzdə birləşdirən komandayıq.', en: 'We are the team that unites all infrastructure, equipment and solutions for events in one center.', ru: 'Мы команда, объединяющая всю инфраструктуру, оборудование и решения для мероприятий в одном центре.', tr: 'Etkinlikler için tüm altyapı, ekipman ve çözümleri tek merkezde birleştiren ekibiz.' },
      visionTagline: { az: 'Bir Mərkəz · Tam Həll', en: 'One Center · Full Solution', ru: 'Один центр · Полное решение', tr: 'Bir Merkez · Tam Çözüm' },
      missionLabel: { az: '02 — Missiya', en: '02 — Mission', ru: '02 — Миссия', tr: '02 — Misyon' },
      missionTitle: { az: 'MİSSİYAMIZ', en: 'OUR MISSION', ru: 'НАША МИССИЯ', tr: 'MİSYONUMUZ' },
      missionBody: { az: 'Hər ideyanın reallaşması üçün lazım olan texniki və fiziki imkanları bir mərkəzdə birləşdirərək etibarlı tərəfdaşa çevrilmək.', en: 'To become a trusted partner by uniting the technical and physical capabilities needed for every idea to come to life in one center.', ru: 'Стать надёжным партнёром, объединив в одном центре технические и физические возможности, необходимые для реализации каждой идеи.', tr: 'Her fikrin hayata geçmesi için gereken teknik ve fiziksel imkânları tek merkezde birleştirerek güvenilir bir ortağa dönüşmek.' },
      stats: [
        { target: 10, suffix: '+', label: { az: 'İllik Təcrübə', en: 'Years Experience', ru: 'Лет опыта', tr: 'Yıl Deneyim' } },
        { target: 1200, suffix: '+', label: { az: 'Uğurlu Layihə', en: 'Successful Projects', ru: 'Успешных проектов', tr: 'Başarılı Proje' } },
        { target: 50, suffix: '+', label: { az: 'Tərəfdaş Brend', en: 'Partner Brands', ru: 'Партнёрских брендов', tr: 'Partner Marka' } },
      ],
    },
    bento: {
      badge: { az: 'Niyə Biz', en: 'Why Us', ru: 'Почему мы', tr: 'Neden Biz' },
      cards: [
        { title: { az: '10 İllik Təcrübə', en: '10 Years Experience', ru: '10 лет опыта', tr: '10 Yıl Deneyim' }, desc: { az: 'Bazarda lider mövqeyimizi qoruyaraq hər zaman ən yaxşısını təklif edirik.', en: 'Maintaining our leading position in the market, we always offer the best.', ru: 'Сохраняя лидирующие позиции на рынке, мы всегда предлагаем лучшее.', tr: 'Piyasadaki lider konumumuzu koruyarak her zaman en iyisini sunuyoruz.' } },
        { title: { az: 'Sürətli Çatdırılma', en: 'Fast Delivery', ru: 'Быстрая доставка', tr: 'Hızlı Teslimat' }, desc: { az: 'Sifarişdən qurğuya qədər hər mərhələ planlanmış və vaxtında.', en: 'Every stage from order to setup is planned and on time.', ru: 'Каждый этап от заказа до монтажа спланирован и выполнен в срок.', tr: 'Siparişten kuruluma kadar her aşama planlanmış ve zamanında.' } },
        { title: { az: 'Tam Zəmanət', en: 'Full Guarantee', ru: 'Полная гарантия', tr: 'Tam Garanti' }, desc: { az: 'Bütün avadanlıqlar sınaqdan keçmiş, hər işdə etibarlılıq əsas şərtimizdir.', en: 'All equipment is tested, reliability in every job is our primary condition.', ru: 'Всё оборудование протестировано, надёжность в каждой работе — наше главное условие.', tr: 'Tüm ekipmanlar test edilmiştir, her işte güvenilirlik temel şartımızdır.' } },
      ],
      imageTitle: { az: 'Peşəkar', en: 'Professional', ru: 'Профессиональная', tr: 'Profesyonel' },
      imageTitleAccent: { az: 'Komanda.', en: 'Team.', ru: 'Команда.', tr: 'Ekip.' },
      image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=900&auto=format&fit=crop',
    },
    team: {
      badge: { az: 'Komanda', en: 'Team', ru: 'Команда', tr: 'Ekip' },
      titleLine1: { az: 'Arxanızda', en: 'Behind You', ru: 'За вами', tr: 'Arkanızda' },
      titleLine2: { az: 'Peşəkarlar.', en: 'Professionals.', ru: 'Профессионалы.', tr: 'Profesyoneller.' },
    },
    values: {
      badge: { az: 'Dəyərlərimiz', en: 'Our Values', ru: 'Наши ценности', tr: 'Değerlerimiz' },
      titleLine1: { az: 'Prinsiplərimiz', en: 'Our Principles', ru: 'Наши принципы', tr: 'İlkelerimiz' },
      titleLine2: { az: 'Əsasımız.', en: 'Our Foundation.', ru: 'Наша основа.', tr: 'Temelimiz.' },
      items: [
        { title: { az: 'Mükəmməllik', en: 'Excellence', ru: 'Совершенство', tr: 'Mükemmellik' }, desc: { az: 'Hər bir işdə ən yüksək nəticəyə can atırıq. Standart bizim üçün başlanğıc nöqtəsidir, hədəf deyil.', en: 'We strive for the highest result in every task. The standard is our starting point, not our goal.', ru: 'Мы стремимся к наивысшему результату в каждом деле. Стандарт для нас — отправная точка, а не цель.', tr: 'Her işte en yüksek sonucu hedefliyoruz. Standart bizim için başlangıç noktasıdır, hedef değil.' } },
        { title: { az: 'Etibarlılıq', en: 'Reliability', ru: 'Надёжность', tr: 'Güvenilirlik' }, desc: { az: 'Verdiyimiz vəd və keyfiyyətə tam zəmanət veririk. Müştərimiz narahat olmamalıdır.', en: 'We fully guarantee our promises and quality. Our clients should not worry.', ru: 'Мы полностью гарантируем свои обещания и качество. Наш клиент не должен беспокоиться.', tr: 'Verdiğimiz sözü ve kaliteyi tam olarak garanti ediyoruz. Müşterimiz endişelenmemelidir.' } },
        { title: { az: 'Müştəri Məmnuniyyəti', en: 'Client Satisfaction', ru: 'Удовлетворённость клиентов', tr: 'Müşteri Memnuniyeti' }, desc: { az: 'Sizin sevincinizdən böyük uğur tanımırıq. Hər tədbiri sizinlə birlikdə yaradırıq.', en: 'We know no greater success than your joy. We create every event together with you.', ru: 'Мы не знаем большего успеха, чем ваша радость. Каждое мероприятие мы создаём вместе с вами.', tr: 'Sizin mutluluğunuzdan büyük bir başarı tanımıyoruz. Her etkinliği sizinle birlikte yaratıyoruz.' } },
      ],
    },
  },
  contact: {
    hero: {
      badge: { az: 'Bizimlə Əlaqə', en: 'Contact Us', ru: 'Свяжитесь с нами', tr: 'Bizimle İletişim' },
      titleLine1: { az: 'Gəlin', en: "Let's", ru: 'Давайте', tr: 'Hadi' },
      titleLine2: { az: 'Danışaq.', en: 'Talk.', ru: 'Поговорим.', tr: 'Konuşalım.' },
      subtitle: { az: 'Tədbiriniz üçün mükəmməl həllər axtarırsınız? Bizimlə əlaqə saxlayın.', en: 'Looking for perfect solutions for your event? Get in touch with us.', ru: 'Ищете идеальные решения для своего мероприятия? Свяжитесь с нами.', tr: 'Etkinliğiniz için mükemmel çözümler mi arıyorsunuz? Bizimle iletişime geçin.' },
    },
    form: {
      labelName: { az: 'Ad Soyad', en: 'Full Name', ru: 'Имя Фамилия', tr: 'Ad Soyad' },
      labelPhone: { az: 'Telefon', en: 'Phone', ru: 'Телефон', tr: 'Telefon' },
      labelEmail: { az: 'Email', en: 'Email', ru: 'Email', tr: 'Email' },
      labelMessage: { az: 'Mesajınız', en: 'Your Message', ru: 'Ваше сообщение', tr: 'Mesajınız' },
      placeholderName: { az: 'Məs: Tural Rəhimov', en: 'E.g. John Smith', ru: 'Напр: Иван Иванов', tr: 'Ör: Ahmet Yılmaz' },
      placeholderPhone: { az: '+994 -- --- -- --', en: '+1 --- --- ----', ru: '+7 --- --- ----', tr: '+90 --- --- ----' },
      placeholderEmail: { az: 'nümunə@mail.com', en: 'example@mail.com', ru: 'пример@mail.com', tr: 'ornek@mail.com' },
      placeholderMessage: { az: 'Tədbiriniz haqqında qısa məlumat...', en: 'Brief information about your event...', ru: 'Краткая информация о вашем мероприятии...', tr: 'Etkinliğiniz hakkında kısa bilgi...' },
      errorRequired: { az: 'Bütün sahələri doldurun', en: 'Please fill in all fields', ru: 'Пожалуйста, заполните все поля', tr: 'Lütfen tüm alanları doldurun' },
      successTitle: { az: 'Mesajınız göndərildi!', en: 'Your message has been sent!', ru: 'Ваше сообщение отправлено!', tr: 'Mesajınız gönderildi!' },
      successBody: { az: 'Ən qısa zamanda sizinlə əlaqə saxlanılacaq.', en: 'We will get back to you as soon as possible.', ru: 'Мы свяжемся с вами в ближайшее время.', tr: 'En kısa sürede sizinle iletişime geçeceğiz.' },
      resetButton: { az: 'Yeni mesaj yaz', en: 'Write a new message', ru: 'Написать новое сообщение', tr: 'Yeni mesaj yaz' },
      submitButton: { az: 'Göndər', en: 'Send', ru: 'Отправить', tr: 'Gönder' },
      infoPhone: { az: 'Telefon', en: 'Phone', ru: 'Телефон', tr: 'Telefon' },
      infoPhoneValue: { az: '+994 50 123 45 67', en: '+994 50 123 45 67', ru: '+994 50 123 45 67', tr: '+994 50 123 45 67' },
      infoPhoneSub: { az: 'Hər gün 09:00 - 21:00', en: 'Every day 09:00 - 21:00', ru: 'Каждый день 09:00 - 21:00', tr: 'Her gün 09:00 - 21:00' },
      infoEmail: { az: 'Email', en: 'Email', ru: 'Email', tr: 'Email' },
      infoEmailValue: { az: 'sales@eventrent.az', en: 'sales@eventrent.az', ru: 'sales@eventrent.az', tr: 'sales@eventrent.az' },
      infoEmailSub: { az: '24 saat ərzində cavab', en: 'Reply within 24 hours', ru: 'Ответ в течение 24 часов', tr: '24 saat içinde yanıt' },
      infoAddress: { az: 'Ünvan', en: 'Address', ru: 'Адрес', tr: 'Adres' },
      infoAddressValue: { az: 'Bakı, Əhməd Rəcəbli küç.', en: 'Baku, Ahmed Rajabli St.', ru: 'Баку, ул. Ахмед Раджабли', tr: 'Bakü, Ahmed Recebli Cad.' },
      infoAddressSub: { az: 'Nərimanov rayonu', en: 'Narimanov district', ru: 'Нариманов район', tr: 'Narimanov ilçesi' },
    },
    cta: {
      badge: { az: 'Əlaqə Nöqtəsi', en: 'Contact Point', ru: 'Точка контакта', tr: 'İletişim Noktası' },
      subText: { az: 'Hər soruşa cavab, hər ideyana həll — sizi gözləyirik.', en: 'An answer to every question, a solution to every idea — we are waiting for you.', ru: 'Ответ на каждый вопрос, решение для каждой идеи — мы ждём вас.', tr: 'Her soruya yanıt, her fikre çözüm — sizi bekliyoruz.' },
      bottomLabel: { az: 'Eventrent · Bakı · Azerbaijan', en: 'Eventrent · Baku · Azerbaijan', ru: 'Eventrent · Баку · Азербайджан', tr: 'Eventrent · Bakü · Azerbaycan' },
      bottomTagline: { az: 'Hər tədbirə xüsusi yanaşma, hər müştəriyə xüsusi qayğı.', en: 'A special approach for every event, special care for every client.', ru: 'Особый подход к каждому мероприятию, особая забота о каждом клиенте.', tr: 'Her etkinliğe özel yaklaşım, her müşteriye özel ilgi.' },
      bottomCta: { az: 'Müraciət Formu', en: 'Contact Form', ru: 'Форма обращения', tr: 'Başvuru Formu' },
      channelPhone: { az: 'Telefon', en: 'Phone', ru: 'Телефон', tr: 'Telefon' },
      channelEmail: { az: 'E-poçt', en: 'Email', ru: 'Эл. почта', tr: 'E-posta' },
      channelMap: { az: 'Ünvan', en: 'Address', ru: 'Адрес', tr: 'Adres' },
      channelInstagram: { az: 'Instagram', en: 'Instagram', ru: 'Instagram', tr: 'Instagram' },
      channelFacebook: { az: 'Facebook', en: 'Facebook', ru: 'Facebook', tr: 'Facebook' },
      channelTagPhone: { az: 'ZƏNG ET', en: 'CALL', ru: 'ЗВОНИТЬ', tr: 'ARA' },
      channelTagEmail: { az: 'YAZ', en: 'WRITE', ru: 'НАПИСАТЬ', tr: 'YAZ' },
      channelTagMap: { az: 'XƏRİTƏ', en: 'MAP', ru: 'КАРТА', tr: 'HARİTA' },
      channelTagInstagram: { az: 'İZLƏ', en: 'FOLLOW', ru: 'СЛЕДИТЬ', tr: 'TAKİP ET' },
      channelTagFacebook: { az: 'BƏYƏNdİ', en: 'LIKE', ru: 'НРАВИТСЯ', tr: 'BEĞEN' },
      channelPhoneValue: { az: '010-255-35-55', en: '010-255-35-55', ru: '010-255-35-55', tr: '010-255-35-55' },
      channelEmailValue: { az: 'sales@eventrent.az', en: 'sales@eventrent.az', ru: 'sales@eventrent.az', tr: 'sales@eventrent.az' },
      channelAddressValue: { az: 'Xocalı Prospekti 55, Bakı', en: 'Khojali Ave 55, Baku', ru: 'Проспект Ходжалы 55, Баку', tr: 'Hocalı Bulvarı 55, Bakü' },
      channelInstagramValue: { az: '@eventrent.az', en: '@eventrent.az', ru: '@eventrent.az', tr: '@eventrent.az' },
      channelFacebookValue: { az: 'Event Rent', en: 'Event Rent', ru: 'Event Rent', tr: 'Event Rent' },
    },
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3039.428490102005!2d49.8712345!3d40.4012345!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDDCsDI0JzA0LjQiTiA0OcKwNTInMTYuNCJF!5e0!3m2!1sen!2saz!4v1620000000000!5m2!1sen!2saz',
    ctaHeroWord: { az: 'BURDAYIQ', en: 'REACH US', ru: 'МЫ ЗДЕСЬ', tr: 'BURADAYIZ' },
    map: {
      overlayTitle: { az: 'Bizim Ofis', en: 'Our Office', ru: 'Наш офис', tr: 'Ofisimiz' },
      overlaySubtitle: { az: 'Gəlin qonağımız olun, tədbirinizi birlikdə planlaşdıraq.', en: 'Come visit us, let\'s plan your event together.', ru: 'Приходите в гости, давайте вместе спланируем ваше мероприятие.', tr: 'Gelin misafirimiz olun, etkinliğinizi birlikte planlayalım.' },
    },
  },
  footer: {
    tagline: { az: 'Azərbaycanın premium tədbirləri üçün aparıcı texniki prodakşn tərəfdaşı.', en: "Azerbaijan's leading technical production partner for premium event solutions.", ru: 'Ведущий партнёр по техническому продакшну для премиальных мероприятий Азербайджана.', tr: "Azerbaycan'ın premium etkinlikleri için önde gelen teknik prodüksiyon ortağı." },
    navHeading: { az: 'Naviqasiya', en: 'Navigation', ru: 'Навигация', tr: 'Navigasyon' },
    contactHeading: { az: 'Əlaqə', en: 'Contact', ru: 'Контакт', tr: 'İletişim' },
    navLinks: [
      { label: { az: 'Ana Səhifə', en: 'Home', ru: 'Главная', tr: 'Ana Sayfa' }, path: '/' },
      { label: { az: 'Xidmətlər', en: 'Services', ru: 'Услуги', tr: 'Hizmetler' }, path: '/services' },
      { label: { az: 'Kataloq', en: 'Catalog', ru: 'Каталог', tr: 'Katalog' }, path: '/catalog' },
      { label: { az: 'Portfolio', en: 'Portfolio', ru: 'Портфолио', tr: 'Portföy' }, path: '/portfolio' },
      { label: { az: 'Haqqımızda', en: 'About', ru: 'О нас', tr: 'Hakkımızda' }, path: '/about' },
      { label: { az: 'Əlaqə', en: 'Contact', ru: 'Контакт', tr: 'İletişim' }, path: '/contact' },
    ],
    whatsappLine: { az: 'Birbaşa Xətt', en: 'Direct Line', ru: 'Прямая линия', tr: 'Doğrudan Hat' },
    whatsappCta: { az: 'WhatsApp\'da yazın', en: 'Contact us on WhatsApp', ru: 'Написать в WhatsApp', tr: 'WhatsApp\'ta yazın' },
    whatsappBadge: { az: 'İndi', en: 'Now', ru: 'Сейчас', tr: 'Şimdi' },
    whatsappHref: 'https://wa.me/994502251515',
    instagramHref: 'https://instagram.com/eventrent.az',
    linkedinHref: 'https://linkedin.com/company/eventrent',
    copyright: { az: '© 2026 EVENTRENT.AZ. BÜTÜN HÜQUQLAR QORUNUR.', en: '© 2026 EVENTRENT.AZ. ALL RIGHTS RESERVED.', ru: '© 2026 EVENTRENT.AZ. ВСЕ ПРАВА ЗАЩИЩЕНЫ.', tr: '© 2026 EVENTRENT.AZ. TÜM HAKLAR SAKLIDIR.' },
    privacyPolicy: { az: 'Məxfilik Siyasəti', en: 'Privacy Policy', ru: 'Политика конфиденциальности', tr: 'Gizlilik Politikası' },
    termsOfService: { az: 'İstifadə Şərtləri', en: 'Terms of Service', ru: 'Условия использования', tr: 'Kullanım Şartları' },
  },
  home: {
    hero: {
      titleLine1: {
        az: 'Səhnə',
        en: 'The Stage',
        ru: 'Сцена',
        tr: 'Sahne',
      },
      titleLine2: {
        az: 'SİZİNDİR',
        en: 'IS YOURS',
        ru: 'ВАША',
        tr: 'SİZİNDİR',
      },
      titleLine3: {
        az: 'Eventrent.az',
        en: 'Eventrent.az',
        ru: 'Eventrent.az',
        tr: 'Eventrent.az',
      },
      subtitle: {
        az: 'Premium event engineering və texniki prodakşn həlləri',
        en: 'Premium event engineering and technical production solutions',
        ru: 'Премиальные решения по инженерии и техническому продакшну мероприятий',
        tr: 'Premium etkinlik mühendisliği ve teknik prodüksiyon çözümleri',
      },
      primaryCta: {
        az: 'Layihəyə başla',
        en: 'Start your project',
        ru: 'Начать проект',
        tr: 'Projeyi başlat',
      },
      secondaryCta: {
        az: 'Showreel izlə',
        en: 'Watch showreel',
        ru: 'Смотреть шоурил',
        tr: 'Showreel izle',
      },
      scrollLabel: { az: 'Diyirla', en: 'Scroll', ru: 'Прокрути', tr: 'Kaydır' },
      sideLabel: { az: 'Təsis. 2016 — Premium Prodakşn', en: 'Est. 2016 — Premium Production', ru: 'Осн. 2016 — Премиум продакшн', tr: 'Kur. 2016 — Premium Prodüksiyon' },
      stats: [
        { label: { az: 'Mükəmməllik', en: 'Excellence', ru: 'Совершенство', tr: 'Mükemmellik' }, value: { az: 'Texniki', en: 'Technical', ru: 'Технический', tr: 'Teknik' } },
        { label: { az: 'Bazar', en: 'Market', ru: 'Рынок', tr: 'Piyasa' }, value: { az: 'Premium', en: 'High-End', ru: 'Высококлассный', tr: 'Üst Düzey' } },
        { label: { az: 'Fokus', en: 'Focus', ru: 'Фокус', tr: 'Odak' }, value: { az: 'Sinematik', en: 'Cinematic', ru: 'Кинематический', tr: 'Sinematik' } },
      ],
      videoPoster: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80&w=2070',
      overlayImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=1600',
      videoSrc: 'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4',
    },
    capabilities: {
      badge: {
        az: 'İmkanlarımız',
        en: 'Capabilities',
        ru: 'Возможности',
        tr: 'Yetkinlikler',
      },
      title: {
        az: 'Texniki',
        en: 'Technical',
        ru: 'Технические',
        tr: 'Teknik',
      },
      titleAccent: {
        az: 'Gücümüz',
        en: 'Power',
        ru: 'Решения',
        tr: 'Gücümüz',
      },
      description: {
        az: 'Böyükmiqyaslı tədbirlər üçün yüksək standartlı texniki infrastrukturu layihələndirir və idarə edirik.',
        en: 'We design and operate high-standard technical infrastructure for large-scale events.',
        ru: 'Проектируем и управляем технической инфраструктурой высокого уровня для масштабных мероприятий.',
        tr: 'Büyük ölçekli etkinlikler için yüksek standartlı teknik altyapı tasarlar ve yönetiriz.',
      },
      cta: {
        az: 'Xidməti araşdır',
        en: 'Explore service',
        ru: 'Подробнее об услуге',
        tr: 'Hizmeti keşfet',
      },
      items: [
        {
          key: 'led',
          title: {
            az: 'LED Ekranlar',
            en: 'LED Displays',
            ru: 'LED Экраны',
            tr: 'LED Ekranlar',
          },
          description: {
            az: 'Qapalı və açıq məkanlar üçün yüksək parlaqlıq və dəqiqlikdə LED həlləri.',
            en: 'High brightness and precision LED solutions for indoor and outdoor venues.',
            ru: 'Решения LED высокой яркости и точности для помещений и открытых площадок.',
            tr: 'İç ve dış mekanlar için yüksek parlaklıkta ve hassas LED çözümleri.',
          },
          image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80&w=1000',
        },
        {
          key: 'sound',
          title: {
            az: 'Səs Sistemləri',
            en: 'Sound Systems',
            ru: 'Звуковые системы',
            tr: 'Ses Sistemleri',
          },
          description: {
            az: 'Konsert və korporativ tədbirlər üçün peşəkar audio mühəndisliyi.',
            en: 'Professional audio engineering for concerts and corporate events.',
            ru: 'Профессиональная аудиоинженерия для концертов и корпоративных мероприятий.',
            tr: 'Konser ve kurumsal etkinlikler için profesyonel ses mühendisliği.',
          },
          image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1000',
        },
        {
          key: 'stage',
          title: {
            az: 'Səhnə və Ferma',
            en: 'Stage & Truss',
            ru: 'Сцена и фермы',
            tr: 'Sahne ve Truss',
          },
          description: {
            az: 'Təhlükəsiz, modul və vizual olaraq güclü səhnə konstruksiyaları.',
            en: 'Safe, modular, and visually strong stage constructions.',
            ru: 'Безопасные, модульные и визуально мощные сценические конструкции.',
            tr: 'Güvenli, modüler ve görsel olarak güçlü sahne yapıları.',
          },
          image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&q=80&w=1000',
        },
        {
          key: 'lighting',
          title: {
            az: 'İşıqlandırma',
            en: 'Event Lighting',
            ru: 'Световые решения',
            tr: 'Aydınlatma',
          },
          description: {
            az: 'Məkanı atmosferə çevirən dinamik və ssenariyə uyğun işıq dizaynı.',
            en: 'Dynamic, scenario-based lighting design that transforms spaces.',
            ru: 'Динамический светодизайн по сценарию, трансформирующий пространство.',
            tr: 'Mekanı dönüştüren dinamik ve senaryoya uygun ışık tasarımı.',
          },
          image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=1000',
        },
      ],
    },
    eventTypes: {
      badge: {
        az: 'Tədbirlər',
        en: 'Events',
        ru: 'Мероприятия',
        tr: 'Etkinlikler',
      },
      title: {
        az: 'Hər Layihəyə',
        en: 'For Every',
        ru: 'К каждому',
        tr: 'Her Projeye',
      },
      titleAccent: {
        az: 'Özəl Yanaşma',
        en: 'Project',
        ru: 'Проекту',
        tr: 'Özel Yaklaşım',
      },
      description: {
        az: 'Biz tədbirlərə sadəcə təşkil olunacaq bir iş kimi baxmırıq. Çünki insanlar bir tədbirin tərtibatını yox, atmosferini xatırlayırlar.',
        en: 'We do not view events simply as tasks to be organized. Because people remember the atmosphere, not just the arrangement.',
        ru: 'Мы не рассматриваем мероприятия просто как задачу. Потому что люди запоминают атмосферу, а не просто организацию.',
        tr: 'Etkinliklere sadece organize edilecek bir iş olarak bakmıyoruz. Çünkü insanlar etkinliğin düzenini değil, atmosferini hatırlar.',
      },
      cta: {
        az: 'Ətraflı məlumat',
        en: 'More details',
        ru: 'Подробнее',
        tr: 'Detaylı bilgi',
      },
      items: [
        {
          id: 'corporate',
          title: {
            az: 'Rəsmi və Korporativ',
            en: 'Official & Corporate',
            ru: 'Официальные и Корпоративные',
            tr: 'Resmi ve Kurumsal',
          },
          subtitle: {
            az: 'Yüksək protokol və dəqiqlik',
            en: 'High Protocol & Precision',
            ru: 'Высокий протокол и точность',
            tr: 'Yüksek Protokol ve Hassasiyet',
          },
          description: {
            az: 'Ciddi protokol və mütləq dəqiqlik tələb edən rəsmi tədbirlər, sammitlər və konfranslar üçün qüsursuz idarəetmə və texniki təminat.',
            en: 'Flawless management and technical support for official events, summits, and conferences requiring strict protocol and absolute precision.',
            ru: 'Безупречное управление и техническое обеспечение официальных мероприятий, саммитов и конференций, требующих строгого протокола и абсолютной точности.',
            tr: 'Ciddi protokol ve mutlak hassasiyet gerektiren resmi etkinlikler, zirveler ve konferanslar için kusursuz yönetim ve teknik altyapı.',
          },
          image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=1000',
        },
        {
          id: 'concerts',
          title: {
            az: 'Konsert və Festivallar',
            en: 'Concerts & Festivals',
            ru: 'Концерты и Фестивали',
            tr: 'Konserler ve Festivaller',
          },
          subtitle: {
            az: 'Emosional enerji və dinamik atmosfer',
            en: 'Emotional Energy & Dynamic Atmosphere',
            ru: 'Эмоциональная энергия и динамичная атмосфера',
            tr: 'Duygusal Enerji ve Dinamik Atmosfer',
          },
          description: {
            az: 'İnsanların yaddaşından silinməyəcək əsl atmosfer yaratmaq üçün nəhəng səhnə, peşəkar səs və vizual işıq sistemləri.',
            en: 'Massive stage, professional sound, and visual lighting systems to create an unforgettable true atmosphere for the audience.',
            ru: 'Масштабные сцены, профессиональный звук и визуальные световые системы для создания незабываемой атмосферы.',
            tr: 'İnsanların hafızasından silinmeyecek gerçek bir atmosfer yaratmak için devasa sahne, profesyonel ses ve görsel ışık sistemleri.',
          },
          image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1000',
        },
        {
          id: 'weddings',
          title: {
            az: 'Fərdi və Özəl Tədbirlər',
            en: 'Private & Special Events',
            ru: 'Частные и Специальные мероприятия',
            tr: 'Özel ve Kişisel Etkinlikler',
          },
          subtitle: {
            az: 'Sizə xüsusi yanaşma',
            en: 'Custom Approach for You',
            ru: 'Особый подход для вас',
            tr: 'Size Özel Yaklaşım',
          },
          description: {
            az: 'Şablonlardan uzaq, tamamilə sizin vizyonunuza, məqsədinizə və brend xarakterinizə uyğunlaşdırılmış kreativ layihələr.',
            en: 'Creative projects away from templates, fully adapted to your vision, goals, and brand character.',
            ru: 'Креативные проекты вдали от шаблонов, полностью адаптированные под ваше видение, цели и характер бренда.',
            tr: 'Şablonlardan uzak, tamamen vizyonunuza, hedeflerinize ve marka karakterinize uyarlanmış yaratıcı projeler.',
          },
          image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=1000',
        },
      ],
    },
    featuredSetups: {
      badge: {
        az: 'Portfolio',
        en: 'Cinematic Portfolio',
        ru: 'Портфолио',
        tr: 'Portföy',
      },
      title: {
        az: 'Seçilmiş',
        en: 'Selected',
        ru: 'Избранные',
        tr: 'Seçili',
      },
      titleAccent: {
        az: 'Səhnələr',
        en: 'Stages',
        ru: 'Сцены',
        tr: 'Sahneler',
      },
      viewAll: {
        az: 'Bütün layihələr',
        en: 'Explore all projects',
        ru: 'Все проекты',
        tr: 'Tüm projeler',
      },
      projects: [
        {
          title: {
            az: 'Formula 1 Azərbaycan Qran Prisi',
            en: 'Formula 1 Azerbaijan GP',
            ru: 'Формула-1 Гран-при Азербайджана',
            tr: 'Formula 1 Azerbaycan GP',
          },
          location: {
            az: 'Bakı şəhər halqası',
            en: 'Baku City Circuit',
            ru: 'Бакинская городская трасса',
            tr: 'Bakü Şehir Pisti',
          },
          category: {
            az: 'Texniki Prodakşn',
            en: 'Technical Production',
            ru: 'Технический продакшн',
            tr: 'Teknik Prodüksiyon',
          },
          image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=1000',
          year: '2025',
        },
        {
          title: {
            az: 'COP29 Dünya Sammiti',
            en: 'COP29 World Summit',
            ru: 'Всемирный саммит COP29',
            tr: 'COP29 Dünya Zirvesi',
          },
          location: {
            az: 'Bakı Olimpiya Stadionu',
            en: 'Baku Olympic Stadium',
            ru: 'Бакинский олимпийский стадион',
            tr: 'Bakü Olimpiyat Stadyumu',
          },
          category: {
            az: 'Tam Audio-Visual',
            en: 'Full Audio-Visual',
            ru: 'Полный аудиовизуал',
            tr: 'Tam Audio-Visual',
          },
          image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=1000',
          year: '2024',
        },
        {
          title: {
            az: 'Bakı Jazz Festivalı',
            en: 'Baku Jazz Festival',
            ru: 'Бакинский джазовый фестиваль',
            tr: 'Bakü Caz Festivali',
          },
          location: {
            az: 'Heydər Əliyev Mərkəzi',
            en: 'Heydar Aliyev Center',
            ru: 'Центр Гейдара Алиева',
            tr: 'Haydar Aliyev Merkezi',
          },
          category: {
            az: 'İşıq dizaynı',
            en: 'Lighting Design',
            ru: 'Светодизайн',
            tr: 'Işık Tasarımı',
          },
          image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80&w=1000',
          year: '2024',
        },
        {
          title: {
            az: 'Milli Gün mərasimi',
            en: 'National Day Celebration',
            ru: 'Празднование национального дня',
            tr: 'Milli Gün Kutlaması',
          },
          location: {
            az: 'Milli Bulvar',
            en: 'National Boulevard',
            ru: 'Национальный бульвар',
            tr: 'Milli Bulvar',
          },
          category: {
            az: 'LED sistemlər',
            en: 'LED Wall Systems',
            ru: 'LED системы',
            tr: 'LED Duvar Sistemleri',
          },
          image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1000',
          year: '2025',
        },
      ],
    },
    process: {
      badge: {
        az: 'Proses',
        en: 'Engineered Workflow',
        ru: 'Процесс',
        tr: 'Süreç',
      },
      title: {
        az: 'Necə',
        en: 'How We',
        ru: 'Как мы',
        tr: 'Nasıl',
      },
      titleAccent: {
        az: 'İcra edirik',
        en: 'Deliver',
        ru: 'Реализуем',
        tr: 'Uyguluyoruz',
      },
      description: {
        az: 'İlk brifdən canlı yayına qədər strukturlaşdırılmış iş axını ilə texniki dəqiqlik təmin edirik.',
        en: 'From first brief to live execution, our structured workflow guarantees technical precision.',
        ru: 'От первого брифа до live-эфира наш структурированный процесс обеспечивает точность.',
        tr: 'İlk briften canlı yürütmeye kadar yapılandırılmış akışla teknik mükemmellik sağlarız.',
      },
      phase: {
        az: 'Mərhələ',
        en: 'Phase',
        ru: 'Этап',
        tr: 'Aşama',
      },
      footer: {
        az: 'Bakı Event Engineering',
        en: 'Baku Event Engineering',
        ru: 'Baku Event Engineering',
        tr: 'Baku Event Engineering',
      },
      steps: [
        {
          title: {
            az: 'Ekspert konsultasiya',
            en: 'Expert Consultation',
            ru: 'Экспертная консультация',
            tr: 'Uzman Danışmanlık',
          },
          description: {
            az: 'Məkan, büdcə və məqsədlərə əsasən texniki strategiyanı formalaşdırırıq.',
            en: 'We shape the technical strategy based on venue, budget, and goals.',
            ru: 'Формируем техническую стратегию с учетом площадки, бюджета и целей.',
            tr: 'Mekan, bütçe ve hedeflere göre teknik stratejiyi belirliyoruz.',
          },
          bg: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&q=80&w=1000',
        },
        {
          title: {
            az: 'Dəqiq mühəndislik',
            en: 'Precise Engineering',
            ru: 'Точное проектирование',
            tr: 'Hassas Mühendislik',
          },
          description: {
            az: '3D vizuallaşdırma və texniki çertyojlarla bütün riskləri öncədən bağlayırıq.',
            en: 'We close risks early with 3D visualization and technical drafting.',
            ru: 'Снижаем риски заранее за счет 3D-визуализации и технических схем.',
            tr: '3D görselleştirme ve teknik çizimlerle riskleri önceden yönetiyoruz.',
          },
          bg: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=1000',
        },
        {
          title: {
            az: 'Quraşdırma',
            en: 'Seamless Setup',
            ru: 'Монтаж',
            tr: 'Kurulum',
          },
          description: {
            az: 'Sertifikatlı komandamız avadanlıq və səhnə qurulumunu standartlara uyğun icra edir.',
            en: 'Our certified team executes stage and equipment installation to standard.',
            ru: 'Сертифицированная команда выполняет монтаж оборудования по стандартам.',
            tr: 'Sertifikalı ekibimiz kurulumu standartlara uygun tamamlar.',
          },
          bg: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=1000',
        },
        {
          title: {
            az: 'Canlı icra',
            en: 'Flawless Execution',
            ru: 'Безупречный лайв',
            tr: 'Kusursuz Uygulama',
          },
          description: {
            az: 'Canlı mərhələdə işıq, səs və vizual keçidləri real vaxtda idarə edirik.',
            en: 'We manage light, sound, and visual transitions live in real time.',
            ru: 'В режиме live управляем светом, звуком и визуальными переходами.',
            tr: 'Canlı yayında ışık, ses ve görsel geçişleri gerçek zamanlı yönetiyoruz.',
          },
          bg: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=1000',
        },
      ],
    },
    metricsEyebrow: {
      text: { az: '[ Rəqəmlərlə BİZ ]', en: '[ BY THE NUMBERS ]', ru: '[ В ЦИФРАХ ]', tr: '[ RAKAMLARLA BİZ ]' },
    },
    finalCtaBadge: {
      text: { az: 'Sifariş Ver', en: 'Get Started', ru: 'Начать', tr: 'Başlayın' },
    },
    clientsEyebrow: {
      badge: { az: 'Etibar Edənlər', en: 'Trusted By', ru: 'Нам доверяют', tr: 'Güvenenler' },
      count: { az: '50+ Brend', en: '50+ Brands', ru: '50+ брендов', tr: '50+ Marka' },
      trustedLabel: { az: 'Güvənilən Brendlər', en: 'Trusted Brands', ru: 'Доверенные бренды', tr: 'Güvenilen Markalar' },
    },
    visionMissionCompact: {
      visionLabel: { az: '01 — Vizyon', en: '01 — Vision', ru: '01 — Видение', tr: '01 — Vizyon' },
      visionBody: { az: 'Tədbir üçün bütün infrastruktur, avadanlıq və həlləri bir mərkəzdə birləşdirən komandayıq.', en: 'We are the team that unites all infrastructure, equipment and solutions for events in one center.', ru: 'Мы команда, объединяющая всю инфраструктуру, оборудование и решения для мероприятий в одном центре.', tr: 'Etkinlikler için tüm altyapı, ekipman ve çözümleri tek merkezde birleştiren ekibiz.' },
      missionLabel: { az: '02 — Missiya', en: '02 — Mission', ru: '02 — Миссия', tr: '02 — Misyon' },
      missionBody: { az: 'İdeyaların reallaşması üçün texniki və fiziki imkanları birləşdirərək, etibarlı təminat tərəfdaşına çevrilmək.', en: 'To become a trusted partner by uniting technical and physical capabilities needed for ideas to come to life.', ru: 'Стать надёжным партнёром, объединив технические и физические возможности, необходимые для реализации идей.', tr: 'Fikirlerin hayata geçmesi için teknik ve fiziksel imkânları birleştirerek güvenilir bir ortağa dönüşmek.' },
    },
    servicesTeaser: {
      badge: { az: 'Nə Təqdim Edirik?', en: 'What We Offer?', ru: 'Что мы предлагаем?', tr: 'Ne Sunuyoruz?' },
      titleLine1: { az: 'Peşəkar', en: 'Professional', ru: 'Профессиональные', tr: 'Profesyonel' },
      titleLine2: { az: 'Xidmətlər.', en: 'Services.', ru: 'Услуги.', tr: 'Hizmetler.' },
      subtitle: { az: 'Tədbirinizin mükəmməl keçməsi üçün lazım olan hər şeyi bir məkanda təqdim edirik.', en: 'Everything you need for a perfect event, all in one place.', ru: 'Всё необходимое для идеального мероприятия — в одном месте.', tr: 'Mükemmel bir etkinlik için ihtiyacınız olan her şeyi tek bir yerde sunuyoruz.' },
    },
    metrics: {
      items: [
        {
          label: {
            az: 'Təcrübə ili',
            en: 'Years Experience',
            ru: 'Лет опыта',
            tr: 'Yıl deneyim',
          },
          value: '10+',
        },
        {
          label: {
            az: 'Tamamlanmış tədbir',
            en: 'Events Completed',
            ru: 'Завершенных мероприятий',
            tr: 'Tamamlanan etkinlik',
          },
          value: '1,200+',
        },
        {
          label: {
            az: 'Avadanlıq vahidi',
            en: 'Inventory Units',
            ru: 'Единиц инвентаря',
            tr: 'Envanter birimi',
          },
          value: '5,000+',
        },
        {
          label: {
            az: 'Məmnun müştəri',
            en: 'Happy Clients',
            ru: 'Довольных клиентов',
            tr: 'Mutlu müşteri',
          },
          value: '450+',
        },
      ],
    },
    catalogGateway: {
      badge: {
        az: 'Avadanlıq İcarəsi',
        en: 'Equipment Rental',
        ru: 'Аренда оборудования',
        tr: 'Ekipman Kiralama',
      },
      title: {
        az: 'Kataloqumuza',
        en: 'Browse Our',
        ru: 'Перейти в',
        tr: 'Kataloğumuzu',
      },
      titleAccent: {
        az: 'Keçin',
        en: 'Inventory',
        ru: 'Каталог',
        tr: 'İnceleyin',
      },
      description: {
        az: 'Peşəkar event texnologiyaları üçün geniş avadanlıq inventarına birbaşa çıxış əldə edin.',
        en: 'Get direct access to a large inventory of professional event technology.',
        ru: 'Получите прямой доступ к большому инвентарю профессиональной event-техники.',
        tr: 'Profesyonel etkinlik teknolojilerinden oluşan geniş envantere doğrudan erişin.',
      },
      cta: {
        az: 'Kataloqa keç',
        en: 'Go to catalog',
        ru: 'Перейти в каталог',
        tr: 'Kataloğa git',
      },
      stats: [
        {
          value: '500+',
          label: {
            az: 'Məhsul',
            en: 'Products',
            ru: 'Товаров',
            tr: 'Ürün',
          },
        },
        {
          value: '24/7',
          label: {
            az: 'Dəstək',
            en: 'Support',
            ru: 'Поддержка',
            tr: 'Destek',
          },
        },
      ],
      image: 'https://images.unsplash.com/photo-1558403194-611308249627?auto=format&fit=crop&q=80&w=1000',
    },
    finalCta: {
      title: {
        az: 'Birlikdə',
        en: 'Ready to',
        ru: 'Готовы',
        tr: 'Birlikte',
      },
      titleAccent: {
        az: 'Quraq?',
        en: 'Collaborate?',
        ru: 'Сотрудничать?',
        tr: 'Başlayalım?',
      },
      description: {
        az: 'Növbəti tədbirinizin texniki konseptini birlikdə planlayaq və reallaşdıraq.',
        en: 'Let us plan and execute the technical concept of your next event together.',
        ru: 'Давайте вместе спланируем и реализуем техническую концепцию вашего следующего мероприятия.',
        tr: 'Bir sonraki etkinliğinizin teknik kurgusunu birlikte planlayıp uygulayalım.',
      },
      primaryCta: {
        az: 'Konsultasiya rezerv et',
        en: 'Book a consultation',
        ru: 'Забронировать консультацию',
        tr: 'Danışmanlık randevusu al',
      },
      secondaryCta: {
        az: 'Satış komandası',
        en: 'Contact sales',
        ru: 'Связаться с отделом продаж',
        tr: 'Satış ekibiyle iletişim',
      },
      email: 'office@eventrent.az',
      phone: '+994 50 225 15 15',
      address: {
        az: 'Bakı, Azərbaycan',
        en: 'Baku, Azerbaijan',
        ru: 'Баку, Азербайджан',
        tr: 'Bakü, Azerbaycan',
      },
    },
    team: {
      badge: {
        az: 'Komanda',
        en: 'Team',
        ru: 'Команда',
        tr: 'Ekip',
      },
      title: {
        az: 'Arxanızda',
        en: 'Behind You',
        ru: 'За вами',
        tr: 'Arkanızda',
      },
      titleAccent: {
        az: 'Peşəkarlar',
        en: 'Professionals',
        ru: 'Профессионалы',
        tr: 'Profesyoneller',
      },
      members: [
        {
          name: {
            az: 'Pərvin Qasımov',
            en: 'Parvin Gasimov',
            ru: 'Парвин Касумов',
            tr: 'Parvin Kasımov',
          },
          role: {
            az: 'Həmtəsisçi / Direktor',
            en: 'Co-founder / Director',
            ru: 'Соучредитель / Директор',
            tr: 'Kurucu / Direktör',
          },
          description: {
            az: 'Tədbir idarəçiliyi və kreativ planlama sahəsində təcrübəli komanda lideridir. Böyükmiqyaslı layihələrin strategiyası, planlaşdırılması və icrasını idarə edir.',
            en: 'An experienced team leader in event management and creative planning. Manages strategy, planning and execution of large-scale projects.',
            ru: 'Опытный руководитель команды в сфере управления мероприятиями и креативного планирования. Управляет стратегией, планированием и реализацией масштабных проектов.',
            tr: 'Etkinlik yönetimi ve yaratıcı planlama alanında deneyimli bir ekip lideridir. Büyük ölçekli projelerin stratejisini, planlamasını ve uygulanmasını yönetir.',
          },
          image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
        },
        {
          name: {
            az: 'Qalib Kazımlı',
            en: 'Galib Kazimli',
            ru: 'Галиб Казымлы',
            tr: 'Galib Kazımlı',
          },
          role: {
            az: 'Həmtəsisçi / İcraçı Direktor',
            en: 'Co-founder / Executive Director',
            ru: 'Соучредитель / Исполнительный директор',
            tr: 'Kurucu / İcra Direktörü',
          },
          description: {
            az: 'Satış strategiyalarının idarə olunması və biznes əlaqələrinin inkişafına rəhbərlik edir. Müştəri münasibətləri və kommersiya yanaşmasını effektiv idarə edir.',
            en: 'Leads sales strategy management and business relationship development. Effectively manages client relations and commercial approach.',
            ru: 'Руководит управлением стратегий продаж и развитием деловых связей. Эффективно управляет клиентскими отношениями и коммерческим подходом.',
            tr: 'Satış stratejilerinin yönetimine ve iş ilişkilerinin gelişimine öncülük eder. Müşteri ilişkilerini ve ticari yaklaşımı etkili bir şekilde yönetir.',
          },
          image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
        },
        {
          name: {
            az: 'Malik Bağırov',
            en: 'Malik Bagirov',
            ru: 'Малик Багиров',
            tr: 'Malik Bağırov',
          },
          role: {
            az: 'Kreativ Direktor',
            en: 'Creative Director',
            ru: 'Креативный директор',
            tr: 'Kreatif Direktör',
          },
          description: {
            az: 'Brend ruhunu müasir trendlərlə birləşdirir. Yaradıcı baxış tərzi və innovativ yanaşması ilə layihələrin konseptual istiqamətini formalaşdırır.',
            en: 'Combines brand spirit with modern trends. Shapes the conceptual direction of projects with a creative vision and innovative approach.',
            ru: 'Объединяет дух бренда с современными тенденциями. Формирует концептуальное направление проектов с помощью творческого видения и инновационного подхода.',
            tr: 'Marka ruhunu modern trendlerle birleştirir. Yaratıcı bakış açısı ve yenilikçi yaklaşımıyla projelerin kavramsal yönünü şekillendirir.',
          },
          image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=400&auto=format&fit=crop',
        },
        {
          name: {
            az: 'Aysel Şirinova',
            en: 'Aysel Shirinova',
            ru: 'Айсель Ширинова',
            tr: 'Aysel Şirinova',
          },
          role: {
            az: 'Satış şöbəsinin müdiri',
            en: 'Head of Sales',
            ru: 'Руководитель отдела продаж',
            tr: 'Satış Bölümü Müdürü',
          },
          description: {
            az: 'Satış proseslərini idarə edir. Komanda performansının artırılmasında effektiv liderlik edir.',
            en: 'Manages sales processes. Provides effective leadership in improving team performance.',
            ru: 'Управляет процессами продаж. Обеспечивает эффективное руководство в повышении производительности команды.',
            tr: 'Satış süreçlerini yönetir. Ekip performansının artırılmasında etkili liderlik sağlar.',
          },
          image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop',
        },
        {
          name: {
            az: 'Yasin Əhmədov',
            en: 'Yasin Ahmadov',
            ru: 'Ясин Ахмедов',
            tr: 'Yasin Ahmedov',
          },
          role: {
            az: 'Layihə meneceri',
            en: 'Project Manager',
            ru: 'Менеджер проектов',
            tr: 'Proje Yöneticisi',
          },
          description: {
            az: 'Dinamik idarəetmə bacarığı və təşkilati yanaşması ilə müxtəlif tədbir və layihələri idarə edir.',
            en: 'Manages various events and projects with dynamic management skills and an organizational approach.',
            ru: 'Управляет различными мероприятиями и проектами с помощью динамичных управленческих навыков и организационного подхода.',
            tr: 'Dinamik yönetim becerileri ve örgütsel yaklaşımıyla çeşitli etkinlik ve projeleri yönetir.',
          },
          image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
        },
        {
          name: {
            az: 'Nərmin Tarverdiyeva',
            en: 'Narmin Tarverdiyeva',
            ru: 'Нармин Тарвердиева',
            tr: 'Nermin Tarverdiyeva',
          },
          role: {
            az: 'Dizayner',
            en: 'Designer',
            ru: 'Дизайнер',
            tr: 'Tasarımcı',
          },
          description: {
            az: 'Vizual konsept və kreativ həllərə rəhbərlik edir. Müasir və estetik yanaşması ilə layihələrə fərqlilik qatar.',
            en: 'Leads visual concepts and creative solutions. Adds distinction to projects with a modern and aesthetic approach.',
            ru: 'Руководит визуальными концепциями и креативными решениями. Придаёт проектам уникальность современным и эстетическим подходом.',
            tr: 'Görsel konsept ve yaratıcı çözümlere öncülük eder. Modern ve estetik yaklaşımıyla projelere farklılık katar.',
          },
          image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop',
        },
        {
          name: {
            az: 'Aysu Məmmədova',
            en: 'Aysu Mammadova',
            ru: 'Айсу Мамедова',
            tr: 'Aysu Memmedova',
          },
          role: {
            az: 'Ofis menecer',
            en: 'Office Manager',
            ru: 'Офис-менеджер',
            tr: 'Ofis Müdürü',
          },
          description: {
            az: 'Rəsmi sənədləşmə və qeydiyyat üzrə mütəxəssis. Layihələr zamanı araşdırma işlərini həyata keçirir.',
            en: 'Specialist in official documentation and registration. Conducts research during projects.',
            ru: 'Специалист по официальной документации и регистрации. Проводит исследования во время проектов.',
            tr: 'Resmi belgeleme ve kayıt uzmanı. Projeler sırasında araştırma çalışmalarını yürütür.',
          },
          image: 'https://images.unsplash.com/photo-1580489944761-9a91e4d51ab7?q=80&w=400&auto=format&fit=crop',
        },
      ],
    },
    clients: {
      badge: {
        az: 'Etibar Edənlər',
        en: 'Trusted By',
        ru: 'Нам доверяют',
        tr: 'Güvenenler',
      },
      title: {
        az: 'Müştərilərimiz',
        en: 'Our Clients',
        ru: 'Наши клиенты',
        tr: 'Müşterilerimiz',
      },
      subtitle: {
        az: '50+ brend bizə etibar edir',
        en: '50+ brands trust us',
        ru: '50+ брендов доверяют нам',
        tr: '50+ marka bize güveniyor',
      },
      clients: [
        { name: 'Heydər Əliyev Fondu', logo: null, url: 'https://heydaraliyevfoundation.az' },
        { name: 'Azərbaycan Turizm Agentliyi', logo: null, url: 'https://tourism.gov.az' },
        { name: 'Rusiya Səfirliyi', logo: null, url: 'https://azerbaijan.mid.ru' },
        { name: 'İçərişəhər Qoruğu', logo: null, url: 'https://icherisheher.gov.az' },
        { name: 'Azərbaycan Güləş Federasiyası', logo: null, url: 'https://wrestling.az' },
        { name: 'Azərbaycan Badminton Federasiyası', logo: null, url: 'https://badminton.az' },
        { name: 'Azərbaycan Cüdo Federasiyası', logo: null, url: 'https://judo.az' },
        { name: 'Abşeron Ticarət Mərkəzi', logo: null, url: 'https://absheron.az' },
        { name: 'Mərkəzi Bank', logo: null, url: 'https://cba.az' },
        { name: 'Paşa Sığorta', logo: null, url: 'https://pashainsurance.az' },
        { name: 'Azal', logo: null, url: 'https://azal.az' },
        { name: 'Tabaterra', logo: null, url: 'https://tabaterra.az' },
        { name: 'Paşa Kapital', logo: null, url: 'https://pashacapital.az' },
        { name: 'Azərsun', logo: null, url: 'https://azersun.com' },
        { name: 'Bazarstore', logo: null, url: 'https://bazarstore.az' },
        { name: 'Norm Sement', logo: null, url: 'https://norm.az' },
        { name: 'Avropa İttifaqı', logo: null, url: 'https://europa.eu' },
        { name: 'Q STP', logo: null, url: 'https://qstp.az' },
        { name: 'Bakı Dövlət Universiteti', logo: null, url: 'https://bsu.edu.az' },
        { name: 'Odlar Yurdu Universiteti', logo: null, url: 'https://oyu.edu.az' },
        { name: 'Azərxalça', logo: null, url: 'https://azerkhalcha.az' },
        { name: 'Paşa Mall', logo: null, url: 'https://pashamall.az' },
        { name: 'SOCAR', logo: '/logos/socar.svg', url: 'https://socar.az' },
      ],
    },
  },
  services: {
    showcase: {
      badge: { az: 'Xidmətlər', en: 'Services', ru: 'Услуги', tr: 'Hizmetler' },
      detailLink: { az: 'Ətraflı', en: 'Details', ru: 'Подробнее', tr: 'Detaylar' },
      items: [
        { num: '01', eyebrow: { az: 'Səhnə avadanlıqları', en: 'Stage Equipment', ru: 'Сценическое оборудование', tr: 'Sahne Ekipmanları' }, title: { az: 'Peşəkar\nSəhnə Qurğusu', en: 'Professional\nStage Setup', ru: 'Профессиональный\nМонтаж сцены', tr: 'Profesyonel\nSahne Kurulumu' }, description: { az: 'Hər ölçüdə tədbirlər üçün yüksək keyfiyyətli səhnə, truss sistemləri, LED ekranlar və texniki infrastruktura.', en: 'High-quality stage, truss systems, LED screens and technical infrastructure for events of any size.', ru: 'Высококачественная сцена, ферменные системы, LED-экраны и техническая инфраструктура для мероприятий любого масштаба.', tr: 'Her ölçekte etkinlik için yüksek kaliteli sahne, truss sistemleri, LED ekranlar ve teknik altyapı.' }, tags: ['Səhnə', 'Truss', 'LED Ekran', 'Texniki Rider'], image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80&w=1000', iconKey: 'stage' },
        { num: '02', eyebrow: { az: 'Səs sistemləri', en: 'Sound Systems', ru: 'Звуковые системы', tr: 'Ses Sistemleri' }, title: { az: 'Kristal Səs\nHər Nöqtəyə', en: 'Crystal Sound\nEverywhere', ru: 'Кристальный звук\nвезде', tr: 'Kristal Ses\nHer Yere' }, description: { az: 'Line array sistemlərdən monitor qurğularına — peşəkar audio mühəndisliyi ilə hər məkanda mükəmməl akustika.', en: 'From line array systems to monitor setups — perfect acoustics everywhere with professional audio engineering.', ru: 'От линейных массивов до мониторных систем — идеальная акустика везде с профессиональной аудиоинженерией.', tr: 'Line array sistemlerden monitör düzeneklerine — profesyonel ses mühendisliğiyle her yerde mükemmel akustik.' }, tags: ['Line Array', 'Subwoofer', 'Monitor', 'Audio Mix'], image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1000', iconKey: 'sound' },
        { num: '03', eyebrow: { az: 'Çap xidmətləri', en: 'Printing Services', ru: 'Печатные услуги', tr: 'Baskı Hizmetleri' }, title: { az: 'Brendinizi\nGörünən Edin', en: 'Make Your\nBrand Visible', ru: 'Сделайте бренд\nзаметным', tr: 'Markanızı\nGörünür Kılın' }, description: { az: 'Banner, rollup, backdrop, branding materialları — yüksək çözünürlüklü geniş format çap, sürətli çatdırılma.', en: 'Banners, rollups, backdrops, branding materials — high-resolution wide format printing, fast delivery.', ru: 'Баннеры, ролл-апы, бэкдропы, брендинговые материалы — широкоформатная печать высокого разрешения, быстрая доставка.', tr: 'Banner, rollup, backdrop, markalama materyalleri — yüksek çözünürlüklü geniş format baskı, hızlı teslimat.' }, tags: ['Banner', 'Rollup', 'Backdrop', 'Branding'], image: 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?auto=format&fit=crop&q=80&w=1000', iconKey: 'printing' },
        { num: '04', eyebrow: { az: 'Dekor xidməti', en: 'Decor Service', ru: 'Услуги декора', tr: 'Dekor Hizmeti' }, title: { az: 'Məkanı\nMəkana Çevir', en: 'Transform\nthe Space', ru: 'Преобрази\nпространство', tr: 'Mekanı\nDönüştür' }, description: { az: 'Fərdi konsept dekorasiya, floral dizayn, tematik qurğular — hər tədbirə özəl estetik atmosfer.', en: 'Individual concept decoration, floral design, thematic setups — unique aesthetic atmosphere for every event.', ru: 'Индивидуальная концептуальная декорация, флористический дизайн, тематические установки — уникальная эстетическая атмосфера для каждого мероприятия.', tr: 'Bireysel konsept dekorasyon, çiçek tasarımı, tematik düzenlemeler — her etkinliğe özgü estetik atmosfer.' }, tags: ['Floral', 'Tematik', 'Fərdi Konsept'], image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=1000', iconKey: 'decor' },
        { num: '05', eyebrow: { az: 'İşıqlandırma', en: 'Lighting', ru: 'Освещение', tr: 'Aydınlatma' }, title: { az: 'Atmosferi\nYaradın', en: 'Create the\nAtmosphere', ru: 'Создай\nАтмосферу', tr: 'Atmosferi\nYaratın' }, description: { az: 'Dinamik və ssenariyə uyğun işıq dizaynı — məkanı atmosferə çevirən peşəkar işıqlandırma həlləri.', en: 'Dynamic scenario-based lighting design — professional lighting solutions that transform spaces into atmospheres.', ru: 'Динамичный световой дизайн по сценарию — профессиональные световые решения, превращающие пространство в атмосферу.', tr: 'Dinamik ve senaryoya uygun ışık tasarımı — mekanları atmosfere dönüştüren profesyonel aydınlatma çözümleri.' }, tags: ['Moving Head', 'LED Par', 'Wash', 'Spot'], image: 'https://images.unsplash.com/photo-1511578314322-d37980f25207?auto=format&fit=crop&q=80&w=1000', iconKey: 'lighting' },
      ],
    },
    grid: {
      badge: { az: 'Xidmətlər', en: 'Services', ru: 'Услуги', tr: 'Hizmetler' },
      titleLine1: { az: 'Nə Təklif', en: 'What We', ru: 'Что мы', tr: 'Ne Sunuyoruz' },
      titleLine2: { az: 'Edirik?', en: 'Offer?', ru: 'Предлагаем?', tr: '?' },
      cta: { az: 'Bütün alt başlıqlar', en: 'All subcategories', ru: 'Все подкатегории', tr: 'Tüm alt başlıklar' },
    },
    categories: [
      {
        id: 'printing',
        path: '/services/printing',
        title: {
          az: 'Çap xidmətləri',
          en: 'Printing services',
          ru: 'Печатные услуги',
          tr: 'Baskı hizmetleri',
        },
        description: {
          az: 'Yüksək keyfiyyətli çap həlləri ilə brendinizi ön plana çıxarın.',
          en: 'Highlight your brand with high-quality printing solutions.',
          ru: 'Выделите бренд с помощью качественных печатных решений.',
          tr: 'Markanızı yüksek kaliteli baskı çözümleriyle öne çıkarın.',
        },
        image: 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?q=80&w=1920&auto=format&fit=crop',
        subItems: [
          {
            id: 'notebook',
            name: {
              az: 'Bloknot',
              en: 'Notebook',
              ru: 'Блокнот',
              tr: 'Defter',
            },
            desc: {
              az: 'Xüsusi dizaynlı korporativ bloknotlar.',
              en: 'Custom-designed corporate notebooks.',
              ru: 'Корпоративные блокноты с индивидуальным дизайном.',
              tr: 'Özel tasarımlı kurumsal defterler.',
            },
            questions: {
              az: ['Ölçü (A4, A5)', 'Vərəq sayı (50, 100)', 'Üz qabığı (Sərt, Yumşaq)', 'Rəng'],
              en: ['Size (A4, A5)', 'Page count (50, 100)', 'Cover type (Hard, Soft)', 'Color'],
              ru: ['Размер (A4, A5)', 'Количество листов (50, 100)', 'Обложка (Твердая, Мягкая)', 'Цвет'],
              tr: ['Boyut (A4, A5)', 'Sayfa sayısı (50, 100)', 'Kapak tipi (Sert, Yumuşak)', 'Renk'],
            },
          },
          {
            id: 'vinyl',
            name: {
              az: 'Vinil',
              en: 'Vinyl',
              ru: 'Винил',
              tr: 'Vinil',
            },
            desc: {
              az: 'Geniş formatlı vinil çapı və montajı.',
              en: 'Large-format vinyl printing and installation.',
              ru: 'Широкоформатная печать и монтаж винила.',
              tr: 'Geniş format vinil baskı ve montaj.',
            },
            questions: {
              az: ['Ölçü (m²)', 'Material növü', 'Laminasiya', 'Montaj xidməti'],
              en: ['Size (m²)', 'Material type', 'Lamination', 'Installation service'],
              ru: ['Размер (м²)', 'Тип материала', 'Ламинация', 'Монтаж'],
              tr: ['Boyut (m²)', 'Malzeme tipi', 'Laminasyon', 'Montaj hizmeti'],
            },
          },
          {
            id: 'rollup',
            name: {
              az: 'Roll-Up',
              en: 'Roll-Up',
              ru: 'Ролл-ап',
              tr: 'Roll-Up',
            },
            desc: {
              az: 'Səyyar reklam stendləri.',
              en: 'Portable advertising stands.',
              ru: 'Мобильные рекламные стенды.',
              tr: 'Taşınabilir reklam standları.',
            },
            questions: {
              az: ['Ölçü (85x200, 100x200)', 'Material keyfiyyəti', 'Mexanizm növü'],
              en: ['Size (85x200, 100x200)', 'Material quality', 'Mechanism type'],
              ru: ['Размер (85x200, 100x200)', 'Качество материала', 'Тип механизма'],
              tr: ['Boyut (85x200, 100x200)', 'Malzeme kalitesi', 'Mekanizma tipi'],
            },
          },
          {
            id: 'pen',
            name: {
              az: 'Qələm',
              en: 'Pen',
              ru: 'Ручка',
              tr: 'Kalem',
            },
            desc: {
              az: 'Brendləşdirilmiş qələmlər və suvenirlər.',
              en: 'Branded pens and promo souvenirs.',
              ru: 'Брендированные ручки и сувениры.',
              tr: 'Markalı kalem ve promosyon ürünleri.',
            },
            questions: {
              az: ['Model', 'Rəng', 'Çap növü (Lazer, UV)'],
              en: ['Model', 'Color', 'Print type (Laser, UV)'],
              ru: ['Модель', 'Цвет', 'Тип печати (Лазер, UV)'],
              tr: ['Model', 'Renk', 'Baskı türü (Lazer, UV)'],
            },
          },
        ],
      },
      {
        id: 'decor',
        path: '/services/decor',
        title: {
          az: 'Dekor xidmətləri',
          en: 'Decor services',
          ru: 'Декор услуги',
          tr: 'Dekor hizmetleri',
        },
        description: {
          az: 'Tədbirləriniz üçün estetik və innovativ dekorasiya həlləri.',
          en: 'Aesthetic and innovative decor solutions for your events.',
          ru: 'Эстетичные и инновационные декор-решения для мероприятий.',
          tr: 'Etkinlikleriniz için estetik ve yenilikçi dekor çözümleri.',
        },
        image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1920&auto=format&fit=crop',
        subItems: [
          {
            id: 'tents',
            name: {
              az: 'Çadırlar',
              en: 'Tents',
              ru: 'Шатры',
              tr: 'Çadırlar',
            },
            desc: {
              az: 'Hər ölçüdə və dizaynda çadırların qurulması.',
              en: 'Tent setup in any size and concept style.',
              ru: 'Установка шатров любых размеров и стилей.',
              tr: 'Her ölçüde ve tasarımda çadır kurulumu.',
            },
            questions: {
              az: ['Ölçü (m²)', 'Qurulma yeri', 'Döşəmə (Xalça, Taxta)', 'İşıqlandırma'],
              en: ['Size (m²)', 'Setup location', 'Flooring (Carpet, Wood)', 'Lighting'],
              ru: ['Размер (м²)', 'Место установки', 'Покрытие (Ковер, Дерево)', 'Освещение'],
              tr: ['Boyut (m²)', 'Kurulum yeri', 'Zemin (Halı, Ahşap)', 'Aydınlatma'],
            },
          },
          {
            id: 'tables-chairs',
            name: {
              az: 'Masa və Oturacaqlar',
              en: 'Tables and Chairs',
              ru: 'Столы и стулья',
              tr: 'Masa ve Sandalyeler',
            },
            desc: {
              az: 'Müasir və klassik mebel icarəsi.',
              en: 'Modern and classic furniture rental.',
              ru: 'Аренда современной и классической мебели.',
              tr: 'Modern ve klasik mobilya kiralama.',
            },
            questions: {
              az: ['Növ (Masa, Oturacaq)', 'Model', 'Rəng', 'Örtük növü'],
              en: ['Type (Table, Chair)', 'Model', 'Color', 'Cover type'],
              ru: ['Тип (Стол, Стул)', 'Модель', 'Цвет', 'Тип покрытия'],
              tr: ['Tür (Masa, Sandalye)', 'Model', 'Renk', 'Kaplama türü'],
            },
          },
          {
            id: 'tableware',
            name: {
              az: 'Qab-Qacaq',
              en: 'Tableware',
              ru: 'Посуда',
              tr: 'Sofra Takımı',
            },
            desc: {
              az: 'Premium qab-qacaq dəstləri.',
              en: 'Premium tableware sets.',
              ru: 'Премиальные наборы посуды.',
              tr: 'Premium sofra takımı setleri.',
            },
            questions: {
              az: ['Dəst növü', 'Nəfər sayı', 'Model'],
              en: ['Set type', 'Guest count', 'Model'],
              ru: ['Тип набора', 'Количество персон', 'Модель'],
              tr: ['Set türü', 'Kişi sayısı', 'Model'],
            },
          },
        ],
      },
      {
        id: 'other',
        path: '/services/other',
        title: {
          az: 'Digər xidmətlər',
          en: 'Other services',
          ru: 'Другие услуги',
          tr: 'Diğer hizmetler',
        },
        description: {
          az: 'Tədbirinizin mükəmməlliyi üçün əlavə peşəkar xidmətlər.',
          en: 'Additional professional services for complete event execution.',
          ru: 'Дополнительные профессиональные услуги для полного цикла мероприятия.',
          tr: 'Etkinliğinizin eksiksiz olması için ek profesyonel hizmetler.',
        },
        image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1920&auto=format&fit=crop',
        subItems: [
          {
            id: 'dj',
            name: {
              az: 'DJ xidməti',
              en: 'DJ service',
              ru: 'DJ услуга',
              tr: 'DJ hizmeti',
            },
            desc: {
              az: 'Peşəkar musiqi tərtibatı.',
              en: 'Professional music curation.',
              ru: 'Профессиональное музыкальное сопровождение.',
              tr: 'Profesyonel müzik kurgusu.',
            },
            questions: {
              az: ['Tədbir növü', 'Müddət (saat)', 'Avadanlıq tələbi'],
              en: ['Event type', 'Duration (hours)', 'Equipment requirement'],
              ru: ['Тип мероприятия', 'Длительность (часы)', 'Требование к оборудованию'],
              tr: ['Etkinlik türü', 'Süre (saat)', 'Ekipman gereksinimi'],
            },
          },
          {
            id: 'singer',
            name: {
              az: 'Müğənni xidməti',
              en: 'Singer service',
              ru: 'Услуга певца',
              tr: 'Sanatçı hizmeti',
            },
            desc: {
              az: 'Canlı musiqi performansı.',
              en: 'Live music performance.',
              ru: 'Живое музыкальное выступление.',
              tr: 'Canlı müzik performansı.',
            },
            questions: {
              az: ['Janr', 'Müddət', 'Səs sistemi tələbi'],
              en: ['Genre', 'Duration', 'Sound system requirement'],
              ru: ['Жанр', 'Длительность', 'Требование к звуковой системе'],
              tr: ['Tarz', 'Süre', 'Ses sistemi gereksinimi'],
            },
          },
          {
            id: 'host',
            name: {
              az: 'Aparıcı xidməti',
              en: 'Host service',
              ru: 'Услуга ведущего',
              tr: 'Sunucu hizmeti',
            },
            desc: {
              az: 'Təcrübəli tədbir aparıcıları.',
              en: 'Experienced event hosts.',
              ru: 'Опытные ведущие мероприятий.',
              tr: 'Deneyimli etkinlik sunucuları.',
            },
            questions: {
              az: ['Tədbir dili', 'Tədbir növü'],
              en: ['Event language', 'Event type'],
              ru: ['Язык мероприятия', 'Тип мероприятия'],
              tr: ['Etkinlik dili', 'Etkinlik türü'],
            },
          },
          {
            id: 'organization',
            name: {
              az: 'Tədbir təşkilatı',
              en: 'Event organization',
              ru: 'Организация мероприятий',
              tr: 'Etkinlik organizasyonu',
            },
            desc: {
              az: 'A-dan Z-yə təşkilatçılıq xidməti.',
              en: 'A-to-Z event organization service.',
              ru: 'Организация мероприятий под ключ.',
              tr: 'A’dan Z’ye etkinlik organizasyonu.',
            },
            questions: {
              az: ['Tədbir növü', 'Qonaq sayı', 'Büdcə aralığı'],
              en: ['Event type', 'Guest count', 'Budget range'],
              ru: ['Тип мероприятия', 'Количество гостей', 'Бюджет'],
              tr: ['Etkinlik türü', 'Misafir sayısı', 'Bütçe aralığı'],
            },
          },
          {
            id: 'designer',
            name: {
              az: 'Dizayner xidməti',
              en: 'Designer service',
              ru: 'Услуги дизайнера',
              tr: 'Tasarım hizmeti',
            },
            desc: {
              az: 'Vizual konseptlərin hazırlanması.',
              en: 'Visual concept design and direction.',
              ru: 'Разработка визуальных концепций.',
              tr: 'Görsel konsept üretimi.',
            },
            questions: {
              az: ['Dizayn növü', 'Müddət'],
              en: ['Design type', 'Timeline'],
              ru: ['Тип дизайна', 'Сроки'],
              tr: ['Tasarım türü', 'Süre'],
            },
          },
        ],
      },
    ],
  },
  cart: {
    heading:        { az: 'Səbətiniz',           en: 'Your Cart',          ru: 'Ваша корзина',       tr: 'Sepetiniz' },
    itemCount:      { az: 'məhsul',              en: 'item(s)',            ru: 'товар(ов)',           tr: 'ürün' },
    empty:          { az: 'Səbətiniz boşdur.',   en: 'Your cart is empty.', ru: 'Ваша корзина пуста.', tr: 'Sepetiniz boş.' },
    browseCatalog:  { az: 'Kataloqa baxın',      en: 'Browse Catalog',     ru: 'Смотреть каталог',   tr: 'Kataloğa göz atın' },
    checkoutTitle:  { az: 'Sifarişi Tamamla',    en: 'Complete Order',     ru: 'Оформить заказ',     tr: 'Siparişi Tamamla' },
    checkoutSub:    { az: 'Məlumatları daxil edərək sifarişi yekunlaşdırın.', en: 'Enter your details to finalize the order.', ru: 'Введите данные для оформления заказа.', tr: 'Siparişi tamamlamak için bilgilerinizi girin.' },
    labelName:      { az: 'Ad Soyad / Şirkət',  en: 'Full Name / Company', ru: 'Имя / Компания',    tr: 'Ad Soyad / Şirket' },
    labelEmail:     { az: 'Email',               en: 'Email',              ru: 'Email',              tr: 'Email' },
    labelPhone:     { az: 'Telefon',             en: 'Phone',              ru: 'Телефон',            tr: 'Telefon' },
    labelLocation:  { az: 'Məkan',               en: 'Location',           ru: 'Место',              tr: 'Konum' },
    labelDate:      { az: 'Tarix',               en: 'Date',               ru: 'Дата',               tr: 'Tarih' },
    placeholderLocation: { az: 'Məkan axtar və ya yazın...', en: 'Search or type location...', ru: 'Поиск или ввод места...', tr: 'Konum ara veya yaz...' },
    placeholderName: { az: 'John Appleseed',     en: 'John Appleseed',     ru: 'Иван Иванов',        tr: 'Ahmet Yılmaz' },
    placeholderPhone: { az: '+994 50 000 00 00', en: '+1 000 000 0000',    ru: '+7 000 000 00 00',   tr: '+90 000 000 0000' },
    submitBtn:      { az: 'Sifarişi Tamamla',    en: 'Complete Order',     ru: 'Оформить заказ',     tr: 'Siparişi Tamamla' },
    submitting:     { az: 'Göndərilir...',       en: 'Sending...',         ru: 'Отправка...',        tr: 'Gönderiliyor...' },
    successTitle:   { az: 'Təşəkkür edirik!',   en: 'Thank you!',         ru: 'Спасибо!',           tr: 'Teşekkürler!' },
    successBody:    { az: 'Sifarişiniz qəbul olundu. Tezliklə sizinlə əlaqə saxlayacağıq.', en: 'Your order has been received. We will contact you shortly.', ru: 'Ваш заказ принят. Мы свяжемся с вами в ближайшее время.', tr: 'Siparişiniz alındı. En kısa sürede sizinle iletişime geçeceğiz.' },
    goProfile:      { az: 'Profilə keç',         en: 'Go to Profile',      ru: 'Перейти в профиль',  tr: 'Profile Git' },
    errorSend:      { az: 'Sifariş göndərilmədi.', en: 'Order could not be sent.', ru: 'Заказ не отправлен.', tr: 'Sipariş gönderilemedi.' },
    errorServer:    { az: 'Serverə qoşulma alınmadı.', en: 'Could not connect to server.', ru: 'Не удалось подключиться к серверу.', tr: 'Sunucuya bağlanılamadı.' },
    loginPromptTitle: { az: 'Sifarişi tamamlamaq üçün daxil olun', en: 'Sign in to complete your order', ru: 'Войдите для оформления заказа', tr: 'Siparişi tamamlamak için giriş yapın' },
    loginPromptBody: { az: 'Səbətinizdəki məhsulları görmək və sifarişi tamamlamaq üçün zəhmət olmasa hesabınıza daxil olun.', en: 'Please sign in to view your cart items and complete your order.', ru: 'Пожалуйста, войдите, чтобы просмотреть корзину и оформить заказ.', tr: 'Sepetinizdeki ürünleri görmek ve siparişi tamamlamak için lütfen giriş yapın.' },
    loginBtn:       { az: 'Daxil ol',            en: 'Sign In',            ru: 'Войти',              tr: 'Giriş Yap' },
    fallbackProduct: { az: 'Xidmət',             en: 'Service',            ru: 'Услуга',             tr: 'Hizmet' },
  },
  product: {
    notFound:       { az: 'Məhsul tapılmadı',    en: 'Product not found',  ru: 'Товар не найден',    tr: 'Ürün bulunamadı' },
    backToCatalog:  { az: 'Kataloqa qayıt',      en: 'Back to Catalog',    ru: 'Назад к каталогу',   tr: 'Kataloğa dön' },
    techSpecs:      { az: 'Texniki Xüsusiyyətlər', en: 'Technical Specs', ru: 'Технические характеристики', tr: 'Teknik Özellikler' },
    addToCart:      { az: 'Sorğuya əlavə et',    en: 'Add to Inquiry',     ru: 'Добавить в запрос',  tr: 'Sorguya ekle' },
    relatedTitle1:  { az: 'Birlikdə',            en: 'Often Used',         ru: 'Часто используется', tr: 'Birlikte' },
    relatedTitle2:  { az: 'İstifadə Olunur.',    en: 'Together.',          ru: 'Вместе.',            tr: 'Kullanılır.' },
    relatedSub:     { az: 'Bu məhsulla tamamlanan digər avadanlıqlar.', en: 'Other equipment that complements this product.', ru: 'Другое оборудование, дополняющее этот товар.', tr: 'Bu ürünü tamamlayan diğer ekipmanlar.' },
    viewAll:        { az: 'Hamısına bax',        en: 'View All',           ru: 'Смотреть все',       tr: 'Tümünü Gör' },
    details:        { az: 'Detallar',            en: 'Details',            ru: 'Подробнее',          tr: 'Detaylar' },
    modalTitle:     { az: 'Sifariş detalları',   en: 'Order details',      ru: 'Детали заказа',      tr: 'Sipariş detayları' },
    qty:            { az: 'SAY',                 en: 'QTY',                ru: 'КОЛ-ВО',            tr: 'ADET' },
    size:           { az: 'ÖLÇÜ (M²)',           en: 'SIZE (M²)',          ru: 'РАЗМЕР (M²)',        tr: 'ÖLÇÜ (M²)' },
    sizePlaceholder: { az: 'Ölçü (m²) daxil edin...', en: 'Enter size (m²)...', ru: 'Введите размер (м²)...', tr: 'Boyut girin (m²)...' },
    material:       { az: 'MATERIAL NÖVÜ',       en: 'MATERIAL TYPE',      ru: 'ТИП МАТЕРИАЛА',      tr: 'MALZEME TÜRÜ' },
    materialPlaceholder: { az: 'Material növü daxil edin...', en: 'Enter material type...', ru: 'Введите тип материала...', tr: 'Malzeme türü girin...' },
    lamination:     { az: 'LAMİNASİYA',          en: 'LAMINATION',         ru: 'ЛАМИНАЦИЯ',          tr: 'LAMİNASYON' },
    laminationPlaceholder: { az: 'Laminasiya daxil edin...', en: 'Enter lamination...', ru: 'Введите ламинацию...', tr: 'Laminasyon girin...' },
    installation:   { az: 'MONTAJ XİDMƏTİ',     en: 'INSTALLATION',       ru: 'МОНТАЖ',             tr: 'MONTAJ HİZMETİ' },
    installationPlaceholder: { az: 'Montaj xidməti daxil edin...', en: 'Enter installation service...', ru: 'Введите услугу монтажа...', tr: 'Montaj hizmeti girin...' },
    addToCartBtn:   { az: 'Səbətə əlavə et',    en: 'Add to Cart',        ru: 'В корзину',          tr: 'Sepete ekle' },
  },
  catalog: {
    hub:            { az: 'Avadanlıq Mərkəzi',   en: 'Equipment Hub',      ru: 'Центр оборудования', tr: 'Ekipman Merkezi' },
    collection:     { az: 'KOLLEKSİYA',          en: 'THE COLLECTION',     ru: 'КОЛЛЕКЦИЯ',          tr: 'KOLEKSİYON' },
    searchPlaceholder: { az: 'Inventar axtar...', en: 'Search inventory...', ru: 'Поиск по инвентарю...', tr: 'Envanter ara...' },
    categories:     { az: 'Kateqoriyalar',       en: 'Categories',         ru: 'Категории',          tr: 'Kategoriler' },
    all:            { az: 'Hamısı',              en: 'All',                ru: 'Все',                tr: 'Tümü' },
    noGear:         { az: 'Məhsul Tapılmadı',    en: 'No Gear Found',      ru: 'Ничего не найдено',  tr: 'Ürün Bulunamadı' },
    noGearSub:      { az: 'Axtarış parametrlərini dəyişin.', en: 'Adjust your search parameters.', ru: 'Измените параметры поиска.', tr: 'Arama parametrelerini ayarlayın.' },
    clearFilters:   { az: 'Filtrləri Təmizlə',   en: 'Clear All Filters',  ru: 'Очистить фильтры',   tr: 'Filtreleri Temizle' },
    heroTitle1:     { az: 'Texniki',             en: 'Technical',          ru: 'Технический',        tr: 'Teknik' },
    heroTitle2:     { az: 'İnventar.',           en: 'Inventory.',         ru: 'Инвентарь.',         tr: 'Envanter.' },
    heroBadge:      { az: 'Avadanlıq Kataloqu',  en: 'Equipment Catalog',  ru: 'Каталог оборудования', tr: 'Ekipman Kataloğu' },
    heroSub:        { az: 'Premium audio-vizual avadanlıqlar — dünyanın aparıcı istehsalçılarından, ən yüksək sənaye standartlarında.', en: 'Premium audio-visual equipment — from the world\'s leading manufacturers, at the highest industry standards.', ru: 'Премиальное аудиовизуальное оборудование — от ведущих мировых производителей, по высочайшим отраслевым стандартам.', tr: 'Premium ses-görüntü ekipmanları — dünyanın önde gelen üreticilerinden, en yüksek sektör standartlarında.' },
  },
  notFound: {
    title:  { az: 'Tapılmadı',                  en: 'Not Found',          ru: 'Не найдено',         tr: 'Bulunamadı' },
    body:   { az: 'Axtardığınız səhifə mövcud deyil və ya köçürülüb.', en: 'The page you are looking for does not exist or has been moved.', ru: 'Страница не существует или была перемещена.', tr: 'Aradığınız sayfa mevcut değil veya taşınmış.' },
    home:   { az: 'Ana Səhifəyə Qayıt',         en: 'Back to Home',       ru: 'На главную',         tr: 'Ana Sayfaya Dön' },
  },
  catering: {
    hero: {
      eyebrow:    { az: 'Dadlı Təcrübə', en: 'Delicious Experience', ru: 'Вкусный Опыт', tr: 'Lezzetli Deneyim' },
      titleLine1: { az: 'Ketrinq', en: 'Catering', ru: 'Кейтеринг', tr: 'Catering' },
      titleLine2: { az: 'Xidməti.', en: 'Service.', ru: 'Сервис.', tr: 'Hizmeti.' },
      subtitle:   { az: 'Tədbirləriniz üçün peşəkar qidalanma və xidmət həlləri.', en: 'Professional catering and service solutions for your events.', ru: 'Профессиональные решения кейтеринга для ваших мероприятий.', tr: 'Etkinlikleriniz için profesyonel yiyecek ve hizmet çözümleri.' },
    },
    content: {
      eyebrow:  { az: 'Peşəkar Mətbəx', en: 'Professional Kitchen', ru: 'Профессиональная Кухня', tr: 'Profesyonel Mutfak' },
      title:    { az: 'Keyfiyyətli Qidalanma, Peşəkar Xidmət', en: 'Quality Food, Professional Service', ru: 'Качественное Питание, Профессиональный Сервис', tr: 'Kaliteli Yemek, Profesyonel Hizmet' },
      subtitle: { az: '"Event Rent" olaraq biz, tədbirlərinizin ləzzətini artırmaq üçün ən yüksək keyfiyyətli ketrinq xidmətini təklif edirik.', en: 'As "Event Rent" we offer the highest quality catering service to enhance the taste of your events.', ru: 'Как "Event Rent" мы предлагаем высококачественный кейтеринг.', tr: '"Event Rent" olarak en yüksek kalitede catering hizmeti sunuyoruz.' },
      menuItems: [
        { title: { az: 'Soyuq Qəlyanaltılar', en: 'Cold Appetizers', ru: 'Холодные Закуски', tr: 'Soğuk Mezeler' }, desc: { az: 'Müxtəlif pendir, ət və tərəvəz çeşidləri.', en: 'Various cheese, meat and vegetable assortments.', ru: 'Различные сыры, мясо и овощи.', tr: 'Çeşitli peynir, et ve sebzeler.' } },
        { title: { az: 'İsti Yeməklər', en: 'Hot Dishes', ru: 'Горячие Блюда', tr: 'Sıcak Yemekler' }, desc: { az: 'Milli və Avropa mətbəxinin ən dadlı nümunələri.', en: 'The most delicious examples of national and European cuisine.', ru: 'Лучшие блюда национальной и европейской кухни.', tr: 'Milli ve Avrupa mutfağının en lezzetli örnekleri.' } },
        { title: { az: 'Desertlər', en: 'Desserts', ru: 'Десерты', tr: 'Tatlılar' }, desc: { az: 'Şirniyyat və meyvə çeşidləri ilə zəngin süfrə.', en: 'A rich table with sweets and fruit assortments.', ru: 'Богатый стол со сладостями и фруктами.', tr: 'Tatlı ve meyve çeşitleriyle zengin sofra.' } },
        { title: { az: 'İçkilər', en: 'Beverages', ru: 'Напитки', tr: 'İçecekler' }, desc: { az: 'Alkoqollu və alkoqolsuz içki menyusu.', en: 'Alcoholic and non-alcoholic beverage menu.', ru: 'Алкогольное и безалкогольное меню.', tr: 'Alkollü ve alkolsüz içecek menüsü.' } },
      ],
      galleryLabel: { az: 'Qalereya', en: 'Gallery', ru: 'Галерея', tr: 'Galeri' },
      galleryImages: [
        'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=600&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1530103043960-ef38714abb15?q=80&w=600&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1551183053-bf91a1d81141?q=80&w=600&auto=format&fit=crop',
      ],
    },
    request: {
      eyebrow:     { az: 'Ketrinq Sifarişi', en: 'Catering Order', ru: 'Заказ Кейтеринга', tr: 'Catering Siparişi' },
      titleLine1:  { az: 'Tədbiriniz üçün', en: 'For your event', ru: 'Для вашего мероприятия', tr: 'Etkinliğiniz için' },
      titleLine2:  { az: 'fərdi menyu.', en: 'a personal menu.', ru: 'персональное меню.', tr: 'kişisel menü.' },
      subtitle:    { az: 'Formu doldurun — peşəkar ketrinq komandamız sizinlə əlaqə saxlayıb tam fərdi menyu planı hazırlasın.', en: 'Fill out the form — our professional catering team will contact you and prepare a fully personalized menu plan.', ru: 'Заполните форму — наша команда свяжется с вами.', tr: 'Formu doldurun — ekibimiz sizinle iletişime geçsin.' },
      features: [
        { az: 'Peşəkar aşpazlar və ofisiantlar', en: 'Professional chefs and waiters', ru: 'Профессиональные повара и официанты', tr: 'Profesyonel aşçılar ve garsonlar' },
        { az: '10-dən 1000+ nəfərə qədər tədbirlər', en: 'Events from 10 to 1000+ guests', ru: 'Мероприятия от 10 до 1000+ человек', tr: '10\'dan 1000+ kişiye kadar etkinlikler' },
        { az: 'Korporativ, toy, ad günü və daha çox', en: 'Corporate, wedding, birthday and more', ru: 'Корпоративные, свадьбы, дни рождения', tr: 'Kurumsal, düğün, doğum günü ve daha fazlası' },
        { az: 'Anında WhatsApp təsdiq mesajı', en: 'Instant WhatsApp confirmation message', ru: 'Мгновенное подтверждение через WhatsApp', tr: 'Anında WhatsApp onay mesajı' },
      ],
      formTitle:      { az: 'Ketrinq Sifarişi', en: 'Catering Order', ru: 'Заказ Кейтеринга', tr: 'Catering Siparişi' },
      formSubtitle:   { az: 'Zəhmət olmasa məlumatları doldurun.', en: 'Please fill in the details.', ru: 'Пожалуйста, заполните данные.', tr: 'Lütfen bilgileri doldurun.' },
      fields: {
        name:      { az: 'Ad Soyad', en: 'Full Name', ru: 'Имя Фамилия', tr: 'Ad Soyad' },
        phone:     { az: 'Telefon', en: 'Phone', ru: 'Телефон', tr: 'Telefon' },
        email:     { az: 'Email', en: 'Email', ru: 'Email', tr: 'Email' },
        guests:    { az: 'Qonaq sayı', en: 'Guest count', ru: 'Количество гостей', tr: 'Misafir sayısı' },
        location:  { az: 'Məkan', en: 'Venue', ru: 'Место', tr: 'Mekan' },
        date:      { az: 'Tarix', en: 'Date', ru: 'Дата', tr: 'Tarih' },
        timeRange: { az: 'Saat aralığı', en: 'Time range', ru: 'Временной диапазон', tr: 'Saat aralığı' },
        format:    { az: 'Tədbir formatı', en: 'Event format', ru: 'Формат мероприятия', tr: 'Etkinlik formatı' },
        menuNote:  { az: 'Menyu haqqında xüsusi istək', en: 'Special menu request', ru: 'Особые пожелания к меню', tr: 'Menü hakkında özel istek' },
      },
      submitBtn:      { az: 'Sifarişi Göndər', en: 'Send Order', ru: 'Отправить заказ', tr: 'Siparişi Gönder' },
      waNote:         { az: 'WhatsApp bildirişi sizə və adminə göndəriləcək.', en: 'WhatsApp notification will be sent to you and the admin.', ru: 'Уведомление WhatsApp будет отправлено вам и администратору.', tr: 'WhatsApp bildirimi size ve admine gönderilecek.' },
      successTitle:   { az: 'Sifarişiniz qəbul edildi!', en: 'Your order has been received!', ru: 'Ваш заказ получен!', tr: 'Siparişiniz alındı!' },
      successSubtitle:{ az: 'WhatsApp nömrənizə təsdiq mesajı göndərildi. Tezliklə sizinlə əlaqə saxlayacağıq.', en: 'A confirmation message has been sent to your WhatsApp. We will contact you soon.', ru: 'На ваш WhatsApp отправлено подтверждение.', tr: 'WhatsApp numaranıza onay mesajı gönderildi.' },
      newOrderBtn:    { az: 'Yeni Sifariş', en: 'New Order', ru: 'Новый заказ', tr: 'Yeni Sipariş' },
      directContactLabel: { az: 'Bilavasitə əlaqə', en: 'Direct contact', ru: 'Прямая связь', tr: 'Doğrudan iletişim' },
      formats: [
        { az: 'Korporativ', en: 'Corporate', ru: 'Корпоратив', tr: 'Kurumsal' },
        { az: 'Toy', en: 'Wedding', ru: 'Свадьба', tr: 'Düğün' },
        { az: 'Nişan', en: 'Engagement', ru: 'Помолвка', tr: 'Nişan' },
        { az: 'Ad günü', en: 'Birthday', ru: 'День рождения', tr: 'Doğum günü' },
        { az: 'Məzuniyyət', en: 'Graduation', ru: 'Выпускной', tr: 'Mezuniyet' },
        { az: 'Açılış', en: 'Opening', ru: 'Открытие', tr: 'Açılış' },
        { az: 'Digər', en: 'Other', ru: 'Другое', tr: 'Diğer' },
      ],
      timeSlots: ['08:00–12:00','10:00–14:00','12:00–16:00','14:00–18:00','16:00–20:00','18:00–22:00','19:00–23:00','20:00–00:00'],
      guestOptions: ['10-20','20-50','50-100','100-200','200-500','500+'],
      labelName:      { az: 'Ad Soyad', en: 'Full Name', ru: 'Имя и Фамилия', tr: 'Ad Soyad' },
      labelPhone:     { az: 'Telefon', en: 'Phone', ru: 'Телефон', tr: 'Telefon' },
      labelEmail:     { az: 'Email', en: 'Email', ru: 'Email', tr: 'Email' },
      labelGuests:    { az: 'Qonaq sayı', en: 'Guest count', ru: 'Кол-во гостей', tr: 'Misafir sayısı' },
      labelLocation:  { az: 'Məkan', en: 'Venue', ru: 'Место', tr: 'Mekan' },
      labelDate:      { az: 'Tarix', en: 'Date', ru: 'Дата', tr: 'Tarih' },
      labelTimeRange: { az: 'Saat aralığı', en: 'Time range', ru: 'Диапазон времени', tr: 'Saat aralığı' },
      labelFormat:    { az: 'Tədbir formatı', en: 'Event format', ru: 'Формат мероприятия', tr: 'Etkinlik formatı' },
      labelMenuNote:  { az: 'Menyu haqqında xüsusi istək', en: 'Special menu request', ru: 'Особые пожелания', tr: 'Özel menü isteği' },
      placeholderName:      { az: 'Adınız', en: 'Your name', ru: 'Ваше имя', tr: 'Adınız' },
      placeholderGuests:    { az: 'Özəl say', en: 'Custom count', ru: 'Своё число', tr: 'Özel sayı' },
      placeholderLocation:  { az: 'Şəhər, küçə, yer adı...', en: 'City, street, venue...', ru: 'Город, улица, место...', tr: 'Şehir, cadde, mekan...' },
      placeholderTimeRange: { az: 'məs: 18:00 – 23:00', en: 'e.g. 18:00 – 23:00', ru: 'напр: 18:00 – 23:00', tr: 'örn: 18:00 – 23:00' },
      placeholderMenuNote:  { az: 'Allerji, xüsusi diyet...', en: 'Allergy, special diet...', ru: 'Аллергия, диета...', tr: 'Alerji, özel diyet...' },
      sendingLabel:   { az: 'Göndərilir...', en: 'Sending...', ru: 'Отправка...', tr: 'Gönderiliyor...' },
      getCodeLabel:   { az: 'Kodu al və davam et', en: 'Get code and continue', ru: 'Получить код', tr: 'Kodu al ve devam et' },
      formBadge:      { az: 'Sifariş formu', en: 'Order form', ru: 'Форма заказа', tr: 'Sipariş formu' },
      otpBadge:       { az: 'Təsdiq kodu', en: 'Verification code', ru: 'Код подтверждения', tr: 'Doğrulama kodu' },
      otpTitle:       { az: 'WhatsApp kodu', en: 'WhatsApp code', ru: 'Код WhatsApp', tr: 'WhatsApp kodu' },
      otpSentTo:      { az: 'nömrəsinə göndərildi', en: 'sent to', ru: 'отправлен на', tr: 'numarasına gönderildi' },
      otpVerifyBtn:   { az: 'Təsdiqlə və Göndər', en: 'Verify and Send', ru: 'Подтвердить и отправить', tr: 'Doğrula ve Gönder' },
      otpVerifyingLabel: { az: 'Yoxlanılır...', en: 'Verifying...', ru: 'Проверка...', tr: 'Doğrulanıyor...' },
      otpNoCode:      { az: 'Kodu almadınız?', en: "Didn't receive the code?", ru: 'Не получили код?', tr: 'Kodu almadınız mı?' },
      otpResend:      { az: 'Yenidən göndər', en: 'Resend', ru: 'Отправить снова', tr: 'Yeniden gönder' },
      otpWait:        { az: 's gözləyin', en: 's wait', ru: 'с ожидания', tr: 's bekleyin' },
      successGuestLabel:    { az: 'Qonaq:', en: 'Guests:', ru: 'Гости:', tr: 'Misafir:' },
      successDateLabel:     { az: 'Tarix:', en: 'Date:', ru: 'Дата:', tr: 'Tarih:' },
      successLocationLabel: { az: 'Məkan:', en: 'Venue:', ru: 'Место:', tr: 'Mekan:' },
      validationRequired:   { az: 'Ad və telefon mütləqdir.', en: 'Name and phone are required.', ru: 'Имя и телефон обязательны.', tr: 'Ad ve telefon zorunludur.' },
    },
  },
  portfolio: {
    hero: {
      eyebrow:  { az: 'Portfolio', en: 'Portfolio', ru: 'Портфолио', tr: 'Portföy' },
      title:    { az: 'Layihələrimiz', en: 'Our Projects', ru: 'Наши Проекты', tr: 'Projelerimiz' },
      subtitle: { az: 'Hər tədbirə özəl yanaşma. Real layihələr, real nəticələr.', en: 'A unique approach to every event. Real projects, real results.', ru: 'Индивидуальный подход к каждому мероприятию.', tr: 'Her etkinliğe özel yaklaşım. Gerçek projeler.' },
    },
    filters: {
      searchPlaceholder: { az: 'Layihə, müştəri...', en: 'Project, client...', ru: 'Проект, клиент...', tr: 'Proje, müşteri...' },
      categoryLabel:     { az: 'Kateqoriya', en: 'Category', ru: 'Категория', tr: 'Kategori' },
      tagsLabel:         { az: 'Etiketlər', en: 'Tags', ru: 'Теги', tr: 'Etiketler' },
      clearLabel:        { az: 'Filtri Sıfırla', en: 'Clear Filters', ru: 'Сбросить фильтры', tr: 'Filtreleri Temizle' },
      allLabel:          { az: 'Hamısı', en: 'All', ru: 'Все', tr: 'Hepsi' },
      emptyLabel:        { az: 'Nəticə tapılmadı', en: 'No results found', ru: 'Результаты не найдены', tr: 'Sonuç bulunamadı' },
    },
  },
  eventgarden: {
    hero: {
      badge:      { az: 'Açıq Hava Etkinlikləri', en: 'Outdoor Events', ru: 'Мероприятия на открытом воздухе', tr: 'Açık Hava Etkinlikleri' },
      titleLine1: { az: 'Event', en: 'Event', ru: 'Event', tr: 'Event' },
      titleLine2: { az: 'Garden.', en: 'Garden.', ru: 'Garden.', tr: 'Garden.' },
      subtitle:   { az: 'Bağça və açıq hava etkinlikləri üçün xüsusi konsept — çadır, dekor, işıqlandırma və səs sistemləri ilə tam həll.', en: 'A special concept for garden and outdoor events — complete solutions with tents, decor, lighting and sound systems.', ru: 'Специальная концепция для уличных мероприятий — полное решение с тентами, декором, освещением и звуком.', tr: 'Bahçe ve açık hava etkinlikleri için özel konsept — çadır, dekor, aydınlatma ve ses sistemleri ile tam çözüm.' },
    },
  },
  tv: {
    hero: {
      badge:      { az: 'Media & Yayım', en: 'Media & Broadcast', ru: 'Медиа и трансляции', tr: 'Medya & Yayın' },
      titleLine1: { az: 'TV &', en: 'TV &', ru: 'TV &', tr: 'TV &' },
      titleLine2: { az: 'Yayım.', en: 'Broadcast.', ru: 'Трансляция.', tr: 'Yayın.' },
      subtitle:   { az: 'Tədbirlərinizin peşəkar yayımı və video həlləri.', en: 'Professional broadcasting and video solutions for your events.', ru: 'Профессиональные трансляции и видеорешения для ваших мероприятий.', tr: 'Etkinlikleriniz için profesyonel yayın ve video çözümleri.' },
    },
  },
  teambuilding: {
    hero: {
      badge:      { az: 'Komanda Ruhu', en: 'Team Spirit', ru: 'Командный дух', tr: 'Takım Ruhu' },
      titleLine1: { az: 'Timbildinq', en: 'Teambuilding', ru: 'Тимбилдинг', tr: 'Takım Oluşturma' },
      titleLine2: { az: 'Həlləri.', en: 'Solutions.', ru: 'Решения.', tr: 'Çözümleri.' },
      subtitle:   { az: 'Komandanızı gücləndirən yaradıcı və interaktiv etkinlik həlləri.', en: 'Creative and interactive event solutions that strengthen your team.', ru: 'Творческие и интерактивные решения для укрепления команды.', tr: 'Takımınızı güçlendiren yaratıcı ve interaktif etkinlik çözümleri.' },
    },
  },
  gallery: {
    hero: {
      badge:      { az: 'Vizual Arxiv', en: 'Visual Archive', ru: 'Визуальный архив', tr: 'Görsel Arşiv' },
      titleLine1: { az: 'Bizim', en: 'Our', ru: 'Наша', tr: 'Bizim' },
      titleLine2: { az: 'Qalereya.', en: 'Gallery.', ru: 'Галерея.', tr: 'Galeri.' },
      subtitle:   { az: 'Tədbirlərimizdən ən yadda qalan və vizual olaraq möhtəşəm anlar.', en: 'The most memorable and visually stunning moments from our events.', ru: 'Самые незабываемые моменты наших мероприятий.', tr: 'Etkinliklerimizden en akılda kalan görsel anlar.' },
    },
    images: [
      { url: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=800&auto=format&fit=crop', category: 'Tədbir' },
      { url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop', category: 'Səhnə' },
      { url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=800&auto=format&fit=crop', category: 'Korporativ' },
      { url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=800&auto=format&fit=crop', category: 'Teambuilding' },
      { url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=800&auto=format&fit=crop', category: 'İşıq' },
      { url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop', category: 'Texnika' },
      { url: 'https://images.unsplash.com/photo-1560472355-536de3962603?q=80&w=800&auto=format&fit=crop', category: 'Təqdimat' },
      { url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=800&auto=format&fit=crop', category: 'Konfrans' },
      { url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=800&auto=format&fit=crop', category: 'Şou' },
      { url: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?q=80&w=800&auto=format&fit=crop', category: 'Konsert' },
      { url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=800&auto=format&fit=crop', category: 'Premium' },
      { url: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?q=80&w=800&auto=format&fit=crop', category: 'Tədbir' },
    ],
  },
};
